
--- Create the database for product reference data
--- to be run by super user, and new database and tables will be owned by superuser

/* To Do:
- add a constraint to product_price to make sure that USD/EURO are always consistent
- query to set the 'current' flag
- query to identify products without current pricing
- figure out if/how the custom type geo can be used
*/

--- Make sure that WAL LEVEL is set to REPLICA to support logical replication 

ALTER SYSTEM SET wal_level = logical; --- this does require a restart

--- Force drop in case it exists. Terminate all existing connections 
--- Not to be used in production
DROP DATABASE IF EXISTS ecommerce_reference_data WITH (FORCE);

CREATE DATABASE ecommerce_reference_data;

--- connect to the ecommerce_reference_data database
\c ecommerce_reference_data

--- add btree_gist extension to define rangetype constraint for product pricing
CREATE EXTENSION btree_gist;

-- create enumerated types for the geographies and currencies

CREATE TYPE sales_geo AS ENUM ('EU', 'US');

CREATE TYPE sales_currency AS ENUM ('USD', 'EURO');


--- products will be in categories (pants, shoes, shirts, accessories, ...)
CREATE TABLE product_category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50),
    description TEXT
);

--- products have brands (Gap, Boss, Armani, Liz Taylor, ...)
CREATE TABLE product_brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50),
    description TEXT
);

--- product: straight-leg jeans from The Gap, low waist jeans from Boss, ... 
--- this is where the descriptions and the images are kept

CREATE TABLE product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_category_id INTEGER REFERENCES product_category (id),
    product_brand_id INTEGER REFERENCES product_brand (id),
    label VARCHAR (50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50) --- the name of the file, not the URL as this will be replicated to local servers
);

-- product_variants are what is actually sold. They have colors, sizes and EAN numbers (article number)
CREATE TABLE product_variant (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER REFERENCES product(id),
    attributes JSONB, --- this is where we will store data abour color, size, etc. Using JSONB gives flexibility
    upc VARCHAR(12) UNIQUE 
);

--- pricing for products is defined by geography and time
--- this uses slowly changing dimensions Type 6 w. start and end date
--- we use DATERANGE in Postgres to show the simplicity of using rangetypes in Postgres
--- needs a constraint to make sure that USD/EURO are always consistent
CREATE TABLE product_variant_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant_id INTEGER REFERENCES product_variant (id),
    price NUMERIC,
    currency sales_currency, --- custom enum type
    geography VARCHAR(3), --- not using enum type as there is a problem with log rep filter def
    validity DATERANGE, --- from when to when is a certain price valid. The lower bound will be excluded and the upper bound included
    current BOOLEAN DEFAULT false,
    --- Constraint makes sure that validity date ranges are unique for each product and geography.
    EXCLUDE USING GIST (product_variant_id WITH =, geography WITH =, validity WITH &&) 
);

ALTER TABLE product_variant_price REPLICA IDENTITY FULL;




/*
Basic simple test data set
*/

INSERT INTO product_category (id, label, description)
    VALUES 
        (1, 'Pants', 'long trousers'),
        (2, 'Shirts', 'long sleeve and short sleeve shirts'),
        (3, 'Blouses', 'long sleeve and short sleeve shirts'),
        (4, 'Footwear', 'Mens and women''s dress shoes');

INSERT INTO product_brand (id, label, description)
    VALUES 
        (1, 'Gap', 'The Gap'),
        (2, 'Boss', 'Boss'),
        (3, 'Diesel', 'Diesel'),
        (4, 'Aéropostale',' Aéropostale Inc., is an American shopping mall–based retailer of casual apparel and accessories, principally aimed at young adults and teenagers.' ),
        (5, 'Levi''s', 'Levi Strauss & Co');

-- 1. Men's Classic Oxford Shirt
INSERT INTO product (id, product_category_id, product_brand_id, label, shortdescription, longdescription)
    VALUES 
        (1, 2, 1,
        'Men''s Classic Oxford Shirt',
        'Timeless men''s Oxford shirt in 100% cotton with button-down collar for a polished look.',
        'This classic Oxford shirt features a relaxed fit, durable mother-of-pearl buttons, and a versatile design perfect for both casual and business casual occasions. Made from breathable 100% cotton for all-day comfort.'
        ),
        (2, 2, 3,
        'Men''s Classic Oxford Shirt',
        'Timeless men''s Oxford shirt in 100% cotton with button-down collar for a polished look.',
        'This classic Oxford shirt features a relaxed fit, durable mother-of-pearl buttons, and a versatile design perfect for both casual and business casual occasions. Made from breathable 100% cotton for all-day comfort.'
        ),
        (3, 2, 4,
        'Men''s Classic Oxford Shirt',
        'Timeless men''s Oxford shirt in 100% cotton with button-down collar for a polished look.',
        'This classic Oxford shirt features a relaxed fit, durable mother-of-pearl buttons, and a versatile design perfect for both casual and business casual occasions. Made from breathable 100% cotton for all-day comfort.'
        );
        
INSERT INTO product_variant (id, product_id, attributes, upc)
    VALUES 
        (1, 1, '{"color": "grey", "size": "34 short"}', '123456789015'),
        (2, 1, '{"color": "grey", "size": "34 regular"}', '123456789016'),
        (3, 1, '{"color": "grey", "size": "34 long"}', '123456789017');


INSERT INTO product_variant_price (id, product_variant_id, price, currency, geography, validity, current)
    VALUES 
    (1, 1, 31.00, 'EURO', 'EU', '[2025-06-01,)', true),
    (2, 1, 29.75, 'EURO', 'EU', '[2025-01-01,2025-06-01)', false),
    (3, 1, 33.50, 'USD', 'US','[2025-01-01,2025-06-01)', false),
    (4, 1, 35.00, 'USD', 'US','[2025-06-01,)', true);

--- stored procedure to adjust the current flag for product_variant_price

CREATE PROCEDURE adjust_current_price ()
    LANGUAGE PLPGSQL
    AS
    --- very inelegant workaround a apparent limitation of logical replication
    --- create list of ids that should be set to true
    --- iterate through the table and update 'current' one at a time
    $$
    BEGIN
    UPDATE product_variant_price SET current=true WHERE id IN 
        (SELECT id from product_variant_price where validity @> current_date);
    /*
        UPDATE product_variant_price 
            SET current=true 
            WHERE validity @> current_date;
        UPDATE product_variant_price 
            SET current=false 
            WHERE NOT validity @> current_date;
    */        
    END;
    $$;        

