--- Create the database for the US ecommerce site
--- to be run by super user, and new database and tables will be owned by superuser

--- Force drop in case it exists. Terminate all existing connections 
--- Not to be used in production

DROP SUBSCRIPTION IF EXISTS us_reference_data_sub;
DROP DATABASE IF EXISTS us_ecommerce_data WITH (FORCE);

CREATE DATABASE us_ecommerce_data;

--- connect to the us_ecommerce_data database
\c us_ecommerce_data

-- create enumerated types for the geographies and currencies

CREATE TYPE sales_geo AS ENUM ('EU', 'US');

CREATE TYPE sales_currency AS ENUM ('USD', 'EURO');

/* these tables are replicacted from reference data */

CREATE TABLE product_category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50),
    description TEXT
);

CREATE TABLE product_brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50),
    description TEXT
);

CREATE TABLE product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_category_id INTEGER REFERENCES product_category (id),
    product_brand_id INTEGER REFERENCES product_brand (id),
    label VARCHAR (50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50) --- the name of the file, not the URL as this will be replicated to local servers
);

CREATE TABLE product_variant (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER REFERENCES product(id),
    attributes JSONB, --- this is where we will store data abour color, size, etc. Using JSONB provides flexibility
    upc VARCHAR(12) UNIQUE 
);

/* product_variant_price does not have all the columns from the reference data as it only needs the currently active
prices for this region */

CREATE TABLE product_variant_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant_id INTEGER REFERENCES product_variant (id),
    price NUMERIC,
    currency sales_currency --- custom enum type
);

/* these tables are not replicated from reference data */

/* simplified inventory model */

CREATE TABLE product_variant_inventory (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant INTEGER REFERENCES product_variant (id),
    qty integer NOT NULL DEFAULT 0
);

/* simplified customer model with single address and multiple phone numbers.
We could  create a JSONB change record that triggers on update?
 */

CREATE TABLE customer (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR (50) NOT NULL,
    phone_number JSONB,
    street_address VARCHAR (100) NOT NULL,
    city VARCHAR (100) NOT NULL,
    postal_code VARCHAR (100) NOT NULL,
    country VARCHAR (100) NOT NULL
);

/* sales transactions and sales transaction */

CREATE TABLE sales_transaction (
    id UUID PRIMARY KEY,
    date DATE NOT NULL,
    customer INTEGER NOT NULL REFERENCES customer (ID)
);

CREATE TABLE sales_transaction_line (
    id UUID PRIMARY KEY,
    sales_transaction UUID NOT NULL REFERENCES sales_transaction (id),
    product_variant INTEGER REFERENCES product_variant (id),
    qty INTEGER NOT NULL DEFAULT 0,
    price NUMERIC  DEFAULT 0
);


/* insert sample data  -- run only after replication started */

/*
INSERT INTO product_variant_inventory (product_variant, qty) 
    VALUES 
        (1, 100), -- 100 shirts size 34 short
        (2, 12), -- 12 of 34 regular
        (3, 59); -- 59 of 34 long

INSERT INTO customer (id, first_name, last_name, phone_number, street_address, city, postal_code, country)
    VALUES 
        (1, 'Marc', 'Linster', '{"home": "+352 621 453 975", "work": "+352 621 794 818", "mobile": "+352 80 37 20"}',
            '40 rue de la montagne', 'Junglinster', 'L-6136', 'Luxembourg'),
        (2, 'Vibhor', 'Kumar', '{"mobile": "617 234 567"}', '10,  Siamese Road', 'Compton', 'MA 01567', 'USA');    

--- create sales transactions 

DROP PROCEDURE IF EXISTS create_sales_transactions;

CREATE PROCEDURE create_sales_transactions (qty_transactions integer)
LANGUAGE PLPGSQL
AS $$
DECLARE 
    random_sales_transaction_id UUID;
    random_customer_id INTEGER;
    random_product_variant_id INTEGER;
    random_date DATE;
    random_product_variant_price NUMERIC;
    random_qty INTEGER;
    nbr_sales_lines INTEGER;
BEGIN
    FOR i in 1 .. qty_transactions LOOP
        --- create the sales transaction
        random_sales_transaction_id := gen_random_uuid();
        --- select a random customer
        SELECT ID INTO random_customer_id FROM customer ORDER BY RANDOM () LIMIT 1;
        --- random date any day last year
        random_date:= current_date - trunc(random () * 365 +1)::INTEGER; 
        --- create the sales transaction
        INSERT INTO sales_transaction (id, date, customer) VALUES (random_sales_transaction_id, random_date, random_customer_id);
        --- add the sales transaction lines
        nbr_sales_lines:= trunc(random() * 5 + 1); -- between 1 and 5 lines per sales transaction
        FOR j in 1 .. nbr_sales_lines LOOP
            --- select the product_variant
            SELECT ID INTO random_product_variant_id FROM product_variant ORDER BY RANDOM () LIMIT 1;
            --- get the price
            SELECT price INTO random_product_variant_price FROM product_variant_price WHERE product_variant_id = random_product_variant_id;
            --- set the quantity
            random_qty := trunc(random() * 3 + 1);
            INSERT INTO sales_transaction_line (id, sales_transaction, product_variant, qty, price)
                    VALUES (gen_random_uuid(), random_sales_transaction_id, random_product_variant_id, 1, random_product_variant_price);
        END LOOP;
    END LOOP;
END $$;

CALL create_sales_transactions (2);

*/