-- =================================================================
--  AI RECOMMENDATIONS FOR E-COMMERCE SYSTEM
--  AUTHOR: AI Agent
--  PURPOSE: Implements AI-powered product recommendations using
--           vector similarity and collaborative filtering.
--  REQUIRES: PostgreSQL 16+ with pgvector extension
-- =================================================================

\echo '[AI SETUP] ==> Setting up AI-powered recommendation system...'

-- =================================================================
--  SECTION 1: ENABLE AI EXTENSIONS
-- =================================================================

\echo '--> Installing pgvector extension...'
CREATE EXTENSION IF NOT EXISTS vector;

-- =================================================================
--  SECTION 2: AI RECOMMENDATION TABLES
-- =================================================================

\echo '--> Creating AI recommendation tables...'

-- Product embeddings for content-based similarity
CREATE TABLE IF NOT EXISTS product_embeddings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    embedding_type TEXT NOT NULL DEFAULT 'description', -- 'description', 'attributes', 'combined'
    embedding vector(384), -- Using 384-dimensional embeddings (common for sentence transformers)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(product_id, embedding_type)
);

-- Customer purchase behavior for collaborative filtering
CREATE TABLE IF NOT EXISTS customer_purchase_profile (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id INTEGER NOT NULL REFERENCES customer(id) ON DELETE CASCADE,
    product_category_id INTEGER NOT NULL REFERENCES product_category(id),
    purchase_frequency INTEGER DEFAULT 0,
    total_spent NUMERIC(10,2) DEFAULT 0.00,
    avg_rating NUMERIC(3,2) DEFAULT 0.00,
    last_purchase_date DATE,
    preference_score NUMERIC(5,4) DEFAULT 0.00, -- Normalized preference score (0-1)
    UNIQUE(customer_id, product_category_id)
);

-- Product similarity cache for performance
CREATE TABLE IF NOT EXISTS product_similarity_cache (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id_1 INTEGER NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    product_id_2 INTEGER NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    similarity_score NUMERIC(5,4) NOT NULL, -- Cosine similarity score (0-1)
    similarity_type TEXT NOT NULL DEFAULT 'embedding', -- 'embedding', 'collaborative', 'hybrid'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(product_id_1, product_id_2, similarity_type),
    CHECK(product_id_1 != product_id_2)
);

-- Customer product ratings (for collaborative filtering)
CREATE TABLE IF NOT EXISTS product_ratings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id INTEGER NOT NULL REFERENCES customer(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    review_text TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(customer_id, product_id)
);

-- Recommendation results cache
CREATE TABLE IF NOT EXISTS recommendation_cache (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id INTEGER NOT NULL REFERENCES customer(id) ON DELETE CASCADE,
    recommended_product_id INTEGER NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    recommendation_type TEXT NOT NULL, -- 'similar_products', 'collaborative', 'hybrid'
    score NUMERIC(5,4) NOT NULL,
    reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP + INTERVAL '24 hours')
);

-- =================================================================
--  SECTION 3: AI RECOMMENDATION INDEXES
-- =================================================================

\echo '--> Creating indexes for AI recommendation performance...'

-- Vector similarity search indexes
CREATE INDEX IF NOT EXISTS idx_product_embeddings_vector ON product_embeddings 
USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- Collaborative filtering indexes
CREATE INDEX IF NOT EXISTS idx_customer_purchase_profile_customer ON customer_purchase_profile(customer_id);
CREATE INDEX IF NOT EXISTS idx_customer_purchase_profile_category ON customer_purchase_profile(product_category_id);
CREATE INDEX IF NOT EXISTS idx_product_ratings_customer ON product_ratings(customer_id);
CREATE INDEX IF NOT EXISTS idx_product_ratings_product ON product_ratings(product_id);
CREATE INDEX IF NOT EXISTS idx_product_ratings_rating ON product_ratings(rating);

-- Similarity cache indexes
CREATE INDEX IF NOT EXISTS idx_product_similarity_cache_product1 ON product_similarity_cache(product_id_1);
CREATE INDEX IF NOT EXISTS idx_product_similarity_cache_product2 ON product_similarity_cache(product_id_2);
CREATE INDEX IF NOT EXISTS idx_product_similarity_cache_score ON product_similarity_cache(similarity_score DESC);

-- Recommendation cache indexes
CREATE INDEX IF NOT EXISTS idx_recommendation_cache_customer ON recommendation_cache(customer_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_cache_expires ON recommendation_cache(expires_at);
CREATE INDEX IF NOT EXISTS idx_recommendation_cache_score ON recommendation_cache(score DESC);

-- =================================================================
--  SECTION 4: AI UTILITY FUNCTIONS
-- =================================================================

\echo '--> Creating AI utility functions...'

-- Function to normalize text for embedding generation
CREATE OR REPLACE FUNCTION normalize_text_for_embedding(input_text TEXT)
RETURNS TEXT AS $$
BEGIN
    -- Remove extra whitespace, convert to lowercase, remove special characters
    RETURN TRIM(REGEXP_REPLACE(LOWER(input_text), '[^a-z0-9\s]', ' ', 'g'));
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Function to create a simple text-based embedding (mock implementation)
-- In production, this would call an external embedding service or model
CREATE OR REPLACE FUNCTION generate_simple_embedding(input_text TEXT)
RETURNS vector(384) AS $$
DECLARE
    normalized_text TEXT;
    words TEXT[];
    word_count BIGINT;
    embedding_array FLOAT[];
    i INTEGER;
    hash_value BIGINT;
BEGIN
    -- Normalize the input text
    normalized_text := normalize_text_for_embedding(input_text);
    words := string_to_array(normalized_text, ' ');
    word_count := array_length(words, 1);
    
    -- Initialize embedding array with zeros
    embedding_array := array_fill(0.0, ARRAY[384]);
    
    -- Generate simple hash-based embeddings
    -- This is a mock implementation - in production use real embeddings
    FOR i IN 1..LEAST(word_count, 384) LOOP
        IF words[i] IS NOT NULL AND words[i] != '' THEN
            hash_value := hashtext(words[i]);
            embedding_array[i] := (hash_value % 1000) / 1000.0;
        END IF;
    END LOOP;
    
    -- Normalize the vector (L2 normalization)
    RETURN embedding_array::vector(384);
END;
$$ LANGUAGE plpgsql;

-- Function to update product embeddings
CREATE OR REPLACE FUNCTION update_product_embeddings()
RETURNS INTEGER AS $$
DECLARE
    product_rec RECORD;
    embedding_text TEXT;
    embedding_vector vector(384);
    updated_count INTEGER := 0;
BEGIN
    FOR product_rec IN 
        SELECT p.id, p.label, p.shortdescription, p.longdescription,
               pc.label as category_label, pb.label as brand_label,
               COALESCE(pv.attributes::text, '{}') as attributes
        FROM product p
        JOIN product_category pc ON p.product_category_id = pc.id
        JOIN product_brand pb ON p.product_brand_id = pb.id
        LEFT JOIN product_variant pv ON p.id = pv.product_id
    LOOP
        -- Combine all product information for embedding
        embedding_text := CONCAT(
            product_rec.label, ' ',
            product_rec.shortdescription, ' ',
            COALESCE(product_rec.longdescription, ''), ' ',
            product_rec.category_label, ' ',
            product_rec.brand_label, ' ',
            product_rec.attributes
        );
        
        -- Generate embedding
        embedding_vector := generate_simple_embedding(embedding_text);
        
        -- Insert or update embedding
        INSERT INTO product_embeddings (product_id, embedding_type, embedding)
        VALUES (product_rec.id, 'combined', embedding_vector)
        ON CONFLICT (product_id, embedding_type) 
        DO UPDATE SET 
            embedding = EXCLUDED.embedding,
            created_at = CURRENT_TIMESTAMP;
            
        updated_count := updated_count + 1;
    END LOOP;
    
    RETURN updated_count;
END;
$$ LANGUAGE plpgsql;

-- =================================================================
--  SECTION 5: SIMILARITY SEARCH FUNCTIONS
-- =================================================================

\echo '--> Creating similarity search functions...'

-- Find similar products using vector similarity
CREATE OR REPLACE FUNCTION find_similar_products(
    input_product_id INTEGER,
    similarity_threshold FLOAT DEFAULT 0.3,
    max_results INTEGER DEFAULT 10
)
RETURNS TABLE(
    product_id BIGINT,
    product_label TEXT,
    brand_label TEXT,
    category_label TEXT,
    similarity_score NUMERIC(5,4),
    price NUMERIC(10,2)
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.id::BIGINT,
        p.label::TEXT,
        pb.label::TEXT,
        pc.label::TEXT,
        ROUND((1 - (pe1.embedding <=> pe2.embedding))::NUMERIC, 4) as similarity_score,
        COALESCE(pvp.price, 0.00) as price
    FROM product_embeddings pe1
    JOIN product_embeddings pe2 ON pe2.embedding_type = pe1.embedding_type
    JOIN product p ON pe2.product_id = p.id
    JOIN product_brand pb ON p.product_brand_id = pb.id
    JOIN product_category pc ON p.product_category_id = pc.id
    LEFT JOIN product_variant pv ON p.id = pv.product_id
    LEFT JOIN product_variant_price pvp ON pv.id = pvp.product_variant_id AND pvp.current = true
    WHERE pe1.product_id = input_product_id
    AND pe2.product_id != input_product_id
    AND (1 - (pe1.embedding <=> pe2.embedding)) >= similarity_threshold
    ORDER BY similarity_score DESC
    LIMIT max_results;
END;
$$ LANGUAGE plpgsql;

-- Search for products similar to a text query
CREATE OR REPLACE FUNCTION search_similar_products_by_text(
    search_text TEXT,
    similarity_threshold FLOAT DEFAULT 0.2,
    max_results BIGINT DEFAULT 10
)
RETURNS TABLE(
    product_id BIGINT,
    product_label TEXT,
    brand_label TEXT,
    category_label TEXT,
    similarity_score NUMERIC(5,4),
    price NUMERIC(10,2)
) AS $$
DECLARE
    search_embedding vector(384);
BEGIN
    -- Generate embedding for search text
    search_embedding := generate_simple_embedding(search_text);
    
    RETURN QUERY
    SELECT 
        p.id::BIGINT,
        p.label::TEXT,
        pb.label::TEXT,
        pc.label::TEXT,
        ROUND((1 - (search_embedding <=> pe.embedding))::NUMERIC, 4) as similarity_score,
        COALESCE(pvp.price, 0.00) as price
    FROM product_embeddings pe
    JOIN product p ON pe.product_id = p.id
    JOIN product_brand pb ON p.product_brand_id = pb.id
    JOIN product_category pc ON p.product_category_id = pc.id
    LEFT JOIN product_variant pv ON p.id = pv.product_id
    LEFT JOIN product_variant_price pvp ON pv.id = pvp.product_variant_id AND pvp.current = true
    WHERE (1 - (search_embedding <=> pe.embedding)) >= similarity_threshold
    ORDER BY similarity_score DESC
    LIMIT max_results;
END;
$$ LANGUAGE plpgsql;

-- =================================================================
--  SECTION 6: COLLABORATIVE FILTERING FUNCTIONS
-- =================================================================

\echo '--> Creating collaborative filtering functions...'

-- Update customer purchase profiles
CREATE OR REPLACE FUNCTION update_customer_purchase_profiles()
RETURNS INTEGER AS $$
DECLARE
    updated_count INTEGER := 0;
BEGIN
    INSERT INTO customer_purchase_profile (
        customer_id, 
        product_category_id, 
        purchase_frequency, 
        total_spent, 
        avg_rating,
        last_purchase_date,
        preference_score
    )
    SELECT 
        st.customer_id,
        p.product_category_id,
        COUNT(*) as purchase_frequency,
        SUM(stl.price_at_sale * stl.qty) as total_spent,
        COALESCE(AVG(pr.rating), 0) as avg_rating,
        MAX(st.transaction_date) as last_purchase_date,
        -- Preference score based on frequency, spending, and ratings
        LEAST(1.0, (
            (COUNT(*) / 10.0) * 0.4 + 
            (SUM(stl.price_at_sale * stl.qty) / 1000.0) * 0.3 +
            (COALESCE(AVG(pr.rating), 3) / 5.0) * 0.3
        )) as preference_score
    FROM sales_transaction st
    JOIN sales_transaction_line stl ON st.id = stl.sales_transaction_id
    JOIN product_variant pv ON stl.product_variant_id = pv.id
    JOIN product p ON pv.product_id = p.id
    LEFT JOIN product_ratings pr ON st.customer_id = pr.customer_id AND p.id = pr.product_id
    GROUP BY st.customer_id, p.product_category_id
    ON CONFLICT (customer_id, product_category_id)
    DO UPDATE SET
        purchase_frequency = EXCLUDED.purchase_frequency,
        total_spent = EXCLUDED.total_spent,
        avg_rating = EXCLUDED.avg_rating,
        last_purchase_date = EXCLUDED.last_purchase_date,
        preference_score = EXCLUDED.preference_score;
        
    GET DIAGNOSTICS updated_count = ROW_COUNT;
    RETURN updated_count;
END;
$$ LANGUAGE plpgsql;

-- Find customers with similar purchase patterns
CREATE OR REPLACE FUNCTION find_similar_customers(
    input_customer_id INTEGER,
    max_results BIGINT DEFAULT 5
)
RETURNS TABLE(
    customer_id INTEGER,
    similarity_score NUMERIC(5,4),
    shared_categories BIGINT
) AS $$
BEGIN
    RETURN QUERY
    WITH customer_preferences AS (
        SELECT 
            cpp1.customer_id as cust1,
            cpp2.customer_id as cust2,
            COUNT(*) as shared_categories,
            -- Cosine similarity based on preference scores
            (SUM(cpp1.preference_score * cpp2.preference_score) / 
             (SQRT(SUM(cpp1.preference_score * cpp1.preference_score)) * 
              SQRT(SUM(cpp2.preference_score * cpp2.preference_score)))) as similarity
        FROM customer_purchase_profile cpp1
        JOIN customer_purchase_profile cpp2 ON cpp1.product_category_id = cpp2.product_category_id
        WHERE cpp1.customer_id = input_customer_id 
        AND cpp2.customer_id != input_customer_id
        GROUP BY cpp1.customer_id, cpp2.customer_id
        HAVING COUNT(*) >= 2  -- At least 2 shared categories
    )
    SELECT 
        cp.cust2,
        ROUND(cp.similarity::NUMERIC, 4),
        cp.shared_categories
    FROM customer_preferences cp
    WHERE cp.similarity > 0.1
    ORDER BY cp.similarity DESC
    LIMIT max_results;
END;
$$ LANGUAGE plpgsql;

-- Generate collaborative filtering recommendations
CREATE OR REPLACE FUNCTION get_collaborative_recommendations(
    input_customer_id INTEGER,
    max_results INTEGER DEFAULT 10
)
RETURNS TABLE(
    product_id BIGINT,
    product_label TEXT,
    brand_label TEXT,
    category_label TEXT,
    recommendation_score NUMERIC(5,4),
    price NUMERIC(10,2),
    reason TEXT
) AS $$
BEGIN
    RETURN QUERY
    WITH similar_customers AS (
        SELECT * FROM find_similar_customers(input_customer_id, 10)
    ),
    customer_purchased AS (
        SELECT DISTINCT p.id as product_id
        FROM sales_transaction st
        JOIN sales_transaction_line stl ON st.id = stl.sales_transaction_id
        JOIN product_variant pv ON stl.product_variant_id = pv.id
        JOIN product p ON pv.product_id = p.id
        WHERE st.customer_id = input_customer_id
    ),
    recommended_products AS (
        SELECT 
            p.id::BIGINT,
            p.label::TEXT,
            pb.label::TEXT as brand_label,
            pc.label::TEXT as category_label,
            ROUND((AVG(sc.similarity_score * COALESCE(pr.rating, 3) / 5.0))::NUMERIC, 4) as score,
            COALESCE(pvp.price, 0.00) as price,
            'Customers with similar preferences also liked this product' as reason
        FROM similar_customers sc
        JOIN sales_transaction st ON sc.customer_id = st.customer_id
        JOIN sales_transaction_line stl ON st.id = stl.sales_transaction_id
        JOIN product_variant pv ON stl.product_variant_id = pv.id
        JOIN product p ON pv.product_id = p.id
        JOIN product_brand pb ON p.product_brand_id = pb.id
        JOIN product_category pc ON p.product_category_id = pc.id
        LEFT JOIN product_ratings pr ON sc.customer_id = pr.customer_id AND p.id = pr.product_id
        LEFT JOIN product_variant_price pvp ON pv.id = pvp.product_variant_id AND pvp.current = true
        WHERE p.id NOT IN (SELECT cp.product_id FROM customer_purchased cp)
        GROUP BY p.id, p.label, pb.label, pc.label, pvp.price
        HAVING COUNT(*) >= 2  -- Recommended by at least 2 similar customers
    )
    SELECT * FROM recommended_products
    ORDER BY score DESC
    LIMIT max_results;
END;
$$ LANGUAGE plpgsql;

-- =================================================================
--  SECTION 7: HYBRID RECOMMENDATION SYSTEM
-- =================================================================

\echo '--> Creating hybrid recommendation system...'

-- Get comprehensive recommendations (content + collaborative)
CREATE OR REPLACE FUNCTION get_hybrid_recommendations(
    input_customer_id INTEGER,
    input_product_id INTEGER DEFAULT NULL,
    max_results INTEGER DEFAULT 10
)
RETURNS TABLE(
    product_id BIGINT,
    product_label TEXT,
    brand_label TEXT,
    category_label TEXT,
    recommendation_score NUMERIC(5,4),
    price NUMERIC(10,2),
    recommendation_type TEXT,
    reason TEXT
) AS $$
BEGIN
    RETURN QUERY
    WITH content_based AS (
        SELECT 
            sp.product_id,
            sp.product_label,
            sp.brand_label,
            sp.category_label,
            sp.similarity_score * 0.6 as score, -- Weight content-based at 60%
            sp.price,
            'content_based' as rec_type,
            'Similar to products you viewed: ' || sp.product_label as reason
        FROM find_similar_products(COALESCE(input_product_id, 1), 0.3, 20) sp
        WHERE input_product_id IS NOT NULL
    ),
    collaborative AS (
        SELECT 
            cr.product_id,
            cr.product_label,
            cr.brand_label,
            cr.category_label,
            cr.recommendation_score * 0.4 as score, -- Weight collaborative at 40%
            cr.price,
            'collaborative' as rec_type,
            cr.reason
        FROM get_collaborative_recommendations(input_customer_id, 20) cr
    ),
    combined AS (
        SELECT * FROM content_based
        UNION ALL
        SELECT * FROM collaborative
    ),
    aggregated AS (
        SELECT 
            c.product_id,
            MAX(c.product_label) as product_label,
            MAX(c.brand_label) as brand_label,
            MAX(c.category_label) as category_label,
            SUM(c.score) as final_score,
            MAX(c.price) as price,
            CASE 
                WHEN COUNT(*) > 1 THEN 'hybrid'
                ELSE MAX(c.rec_type)
            END as rec_type,
            STRING_AGG(DISTINCT c.reason, '; ') as combined_reason
        FROM combined c
        GROUP BY c.product_id
    )
    SELECT 
        a.product_id::BIGINT,
        a.product_label,
        a.brand_label,
        a.category_label,
        ROUND(LEAST(a.final_score, 1.0)::NUMERIC, 4) as recommendation_score,
        a.price,
        a.rec_type,
        a.combined_reason
    FROM aggregated a
    ORDER BY recommendation_score DESC
    LIMIT max_results;
END;
$$ LANGUAGE plpgsql;

\echo '[AI SETUP] ==> AI recommendation system setup complete!'
\echo '==> Available functions:'
\echo '    - update_product_embeddings(): Generate embeddings for all products'
\echo '    - find_similar_products(product_id): Find products similar to a given product'
\echo '    - search_similar_products_by_text(text): Search products by text similarity'
\echo '    - update_customer_purchase_profiles(): Update customer behavior profiles'
\echo '    - get_collaborative_recommendations(customer_id): Get collaborative filtering recommendations'
\echo '    - get_hybrid_recommendations(customer_id, [product_id]): Get hybrid recommendations'
