-- =================================================================
--  PSQL SCRIPT FOR E-COMMERCE REFERENCE DATA SETUP
-- =================================================================
--  OWNER: Superuser
--  PURPOSE: Creates the database schema, tables
--           for product reference information.
-- =================================================================

-- =================================================================
--  SECTION 1: SYSTEM AND DATABASE PREPARATION
-- =================================================================
-- Note: These initial commands should be run by a superuser connected
-- to a maintenance database (like 'postgres').

\echo '[SYSTEM PREP] ==> Setting WAL_LEVEL to logical for replication...'
-- This requires a server restart to take effect. It only needs to be
-- run once per PostgreSQL instance.
ALTER SYSTEM SET wal_level = logical;
\echo 'NOTE: A server restart is required for WAL_LEVEL change to apply.'


\echo '[DATABASE PREP] ==> Preparing to drop and recreate the database.'
-- Terminate all active connections to the target database before dropping it.
-- This is a more controlled approach than using WITH (FORCE).
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = 'ecommerce_reference_data' AND pid <> pg_backend_pid();

DROP DATABASE IF EXISTS ecommerce_reference_data;

\echo '[DATABASE PREP] ==> Creating the database...'
CREATE DATABASE ecommerce_reference_data;

-- Switch connection to the newly created database.
\c ecommerce_reference_data

\echo '--> Successfully connected to database: ecommerce_reference_data'

\echo '--> Creating the schemata for api, product_refence, inventory, customer, and sales data'

CREATE SCHEMA IF NOT EXISTS api;
CREATE SCHEMA IF NOT EXISTS product_reference; -- replicated to us/eu_ecommerce_data.product_reference.*
CREATE SCHEMA IF NOT EXISTS internal;

\echo '--> Creating the search path at the database level'

ALTER DATABASE ecommerce_reference_data SET SEARCH_PATH TO api, product_reference, internal; -- permanent change
SET SEARCH_PATH TO api, product_reference, internal; --- make sure path is available in current session

-- =================================================================
--  SECTION 2: EXTENSIONS AND CUSTOM TYPES
-- =================================================================

\echo '--> Creating extensions...'
-- btree_gist is required for using the GIST exclusion constraint on a DATERANGE.
CREATE EXTENSION IF NOT EXISTS btree_gist;

\echo '--> Creating custom ENUM types...'
-- Using ENUMs helps ensure data integrity for controlled vocabularies.
CREATE TYPE internal.sales_geo AS ENUM ('EU', 'US');
CREATE TYPE internal.sales_currency AS ENUM ('USD', 'EURO');


-- =================================================================
--  SECTION 3: TABLE DEFINITIONS
-- =================================================================

\echo '--> Creating product_reference tables...'

CREATE SCHEMA IF NOT EXISTS product_reference;

CREATE TABLE product_reference.product_category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product_reference.product_brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product_reference.product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_category_id INTEGER NOT NULL REFERENCES product_reference.product_category (id),
    product_brand_id INTEGER NOT NULL REFERENCES product_reference.product_brand (id),
    label VARCHAR (50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50)
);

CREATE TABLE product_reference.product_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product_reference.product (id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    currency VARCHAR(4) NOT NULL,
    geography VARCHAR(4) NOT NULL,
    -- DATERANGE where the lower bound is inclusive, and the upper bound is exclusive.
    validity DATERANGE NOT NULL,
    current BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT check_currency_geo_consistency CHECK (
        (geography = 'US' AND currency = 'USD') OR
        (geography = 'EU' AND currency = 'EURO')
    ),
    -- Ensures that there are no overlapping price validity periods for the same product variant and geography.
    EXCLUDE USING GIST (product_id WITH =, geography WITH =, validity WITH &&)
);

-- Set REPLICA IDENTITY to FULL for the table that has row-filtered replication.
-- This ensures that old row data is available for logical replication updates.
ALTER TABLE product_reference.product_price REPLICA IDENTITY FULL;


-- =================================================================
--  SECTION 4: STORED PROCEDURES AND MAINTENANCE QUERIES
-- =================================================================

\echo '--> Creating stored procedures for data maintenance...'

-- [IMPROVEMENT] Rewritten procedure to be more efficient.
CREATE OR REPLACE PROCEDURE api.update_current_price_flags()
    LANGUAGE SQL
    AS $$
    UPDATE product_reference.product_price
    SET current = (validity @> current_date);
$$;

\echo '--> Example maintenance queries:'
\echo '    1. To run the procedure to update all flags: CALL update_current_price_flags();'
\echo '    2. To find products/variants without a current valid price:'

-- [IMPROVEMENT] Query to find variants without a current price.
/*
--- needs rework
SELECT
    v.id AS variant_id,
    v.upc,
    p.label AS product_label
FROM
    product_reference.product p
JOIN
    product_reference.product p ON v.product_id = p.id
WHERE NOT EXISTS (
    SELECT 1
    FROM product_reference.product_price pp
    WHERE pp.product_id = v.id AND pvp.current = true
);
*/

\echo '*** Script Finished Successfully ***'
