-- =================================================================
--  PSQL SCRIPT FOR E-COMMERCE REFERENCE DATA SETUP
-- =================================================================
--  OWNER: Superuser
--  PURPOSE: Creates the database schema, tables, and initial data
--           for product reference information.
-- =================================================================

-- =================================================================
--  SECTION 1: SYSTEM AND DATABASE PREPARATION
-- =================================================================
-- Note: These initial commands should be run by a superuser connected
-- to a maintenance database (like 'postgres').

\echo '[SYSTEM PREP] ==> Setting WAL_LEVEL to logical for replication...'
-- This requires a server restart to take effect. It only needs to be
-- run once per PostgreSQL instance.
ALTER SYSTEM SET wal_level = logical;
\echo 'NOTE: A server restart is required for WAL_LEVEL change to apply.'


\echo '[DATABASE PREP] ==> Preparing to drop and recreate the database.'
-- Terminate all active connections to the target database before dropping it.
-- This is a more controlled approach than using WITH (FORCE).
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = 'ecommerce_reference_data' AND pid <> pg_backend_pid();

DROP DATABASE IF EXISTS ecommerce_reference_data;

\echo '[DATABASE PREP] ==> Creating the database...'
CREATE DATABASE ecommerce_reference_data;

-- Switch connection to the newly created database.
\c ecommerce_reference_data

\echo '--> Successfully connected to database: ecommerce_reference_data'


-- =================================================================
--  SECTION 2: EXTENSIONS AND CUSTOM TYPES
-- =================================================================

\echo '--> Creating extensions...'
-- btree_gist is required for using the GIST exclusion constraint on a DATERANGE.
CREATE EXTENSION IF NOT EXISTS btree_gist;

\echo '--> Creating custom ENUM types...'
-- Using ENUMs helps ensure data integrity for controlled vocabularies.
CREATE TYPE sales_geo AS ENUM ('EU', 'US');
CREATE TYPE sales_currency AS ENUM ('USD', 'EURO');


-- =================================================================
--  SECTION 3: TABLE DEFINITIONS
-- =================================================================

\echo '--> Creating application tables...'

CREATE TABLE product_category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product_brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_category_id INTEGER NOT NULL REFERENCES product_category (id),
    product_brand_id INTEGER NOT NULL REFERENCES product_brand (id),
    label VARCHAR (50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50)
);

CREATE TABLE product_variant (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    attributes JSONB,
    upc VARCHAR(12) UNIQUE NOT NULL
);

CREATE TABLE product_variant_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant_id INTEGER NOT NULL REFERENCES product_variant (id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    currency sales_currency NOT NULL,
    /*
     * DEV NOTE on `geography`:
     * Using VARCHAR(3) instead of the `sales_geo` ENUM is the correct workaround
     * for a known limitation in PostgreSQL where filtered logical replication
     * (e.g., WHERE geography = 'US') does not work with ENUM types.
    */
    geography VARCHAR(3) NOT NULL,
    -- DATERANGE where the lower bound is inclusive, and the upper bound is exclusive.
    validity DATERANGE NOT NULL,
    current BOOLEAN NOT NULL DEFAULT false,

    -- [IMPROVEMENT] Constraint to ensure currency matches the geography.
    CONSTRAINT check_currency_geo_consistency CHECK (
        (geography = 'US' AND currency = 'USD') OR
        (geography = 'EU' AND currency = 'EURO')
    ),

    -- Ensures that there are no overlapping price validity periods for the same product variant and geography.
    EXCLUDE USING GIST (product_variant_id WITH =, geography WITH =, validity WITH &&)
);

-- Set REPLICA IDENTITY to FULL for the table that has row-filtered replication.
-- This ensures that old row data is available for logical replication updates.
ALTER TABLE product_variant_price REPLICA IDENTITY FULL;


-- =================================================================
--  SECTION 4: TEST DATA INSERTION
-- =================================================================

\echo '--> Inserting test data...'
-- Using OVERRIDING SYSTEM VALUE to control the IDs for predictable testing.
INSERT INTO product_category (id, label, description)
    VALUES
        (1, 'Pants', 'long trousers'),
        (2, 'Shirts', 'long sleeve and short sleeve shirts'),
        (3, 'Blouses', 'long sleeve and short sleeve shirts for women'),
        (4, 'Footwear', 'Mens and womens dress shoes')
    ON CONFLICT (id) DO NOTHING;

INSERT INTO product_brand (id, label, description)
    VALUES
        (1, 'Gap', 'The Gap'),
        (2, 'Boss', 'Boss'),
        (3, 'Diesel', 'Diesel'),
        (4, 'Aéropostale',' Aéropostale Inc., is an American shopping mall–based retailer.'),
        (5, 'Levis', 'Levi Strauss & Co') -- Removed apostrophe for simplicity in labels
    ON CONFLICT (id) DO NOTHING;

INSERT INTO product (id, product_category_id, product_brand_id, label, shortdescription)
    VALUES
        (1, 2, 1, 'Mens Classic Oxford Shirt', 'Timeless mens Oxford shirt in 100% cotton.'),
        (2, 2, 3, 'Mens Diesel T-Shirt', 'Graphic T-shirt from Diesel.'),
        (3, 1, 5, '501 Original Fit Jeans', 'The original blue jean since 1873.')
    ON CONFLICT (id) DO NOTHING;

/* add longdescriptions */

--- Oxford Shirt (product 1)
UPDATE product 
    SET longdescription = 
        'The Oxford button-down shirt is a cornerstone of classic American style, revered for its 
        effortless versatility, timeless design, and understated elegance. Originating in the early 20th century, 
        it was popularized by Brooks Brothers, who adapted the button-down collar from English polo players to prevent 
        flapping during matches. Made from Oxford cloth—a durable, slightly textured basketweave cotton—this shirt 
        strikes the perfect balance between casual and refined, making it a go-to for both professional and leisure wear.
        The defining feature is its soft-rolling button-down collar, which adds a touch of relaxed sophistication, distinguishing it 
        from dressier formal shirts. Available in a range of essential colors (crisp white, light blue, pale pink) and 
        subtle patterns (university stripes, tattersall checks, or classic solids), it effortlessly pairs with chinos, jeans, 
        blazers, or suits. The slightly thicker Oxford fabric ensures durability while remaining breathable and comfortable for all-day wear.
        Designed with a traditional fit (though slim and modern cuts are also available), it features a button-through front, single 
        chest pocket (optional), and reinforced stitching for longevity. Whether dressed up with a tie and wool trousers or worn 
        casually with rolled sleeves and shorts, the Oxford button-down transitions seamlessly from office to weekend. A favorite 
        among preppy, Ivy League, and business-casual wardrobes, it remains a wardrobe essential—a symbol of enduring style 
        that never goes out of fashion.'
    WHERE id = 1;

--- Diesel T-Shirt (product 2)

UPDATE product 
    SET longdescription =
        'Men’s Diesel T-Shirt: Bold, Edgy, and Unapologetically Cool
        The Men’s Diesel T-Shirt embodies the brand’s rebellious spirit and Italian craftsmanship, blending streetwear attitude with premium quality. Designed for the confident, fashion-forward man, it features soft, heavyweight cotton for a structured yet comfortable fit, ensuring durability and effortless style. Diesel’s signature distressed detailing, bold graphics, or minimalist logo prints make a statement, whether you’re rocking it with ripped jeans, tailored joggers, or a leather jacket.
        Cut for a slim or relaxed fit (depending on the style), it offers a modern silhouette that flatters without restricting movement. The reinforced stitching, double-stitched hems, and high-quality screen-printing ensure long-lasting wear, even after repeated washes. From classic crewnecks to edgy oversized cuts, Diesel’s T-shirts cater to diverse tastes—whether you prefer understated monochrome styles or eye-catching, avant-garde designs.
        Perfect for layering under a blazer for a high-low look or wearing solo for casual streetwear vibes, this T-shirt is a versatile staple in any contemporary wardrobe. With its unmistakable Diesel edge, it’s more than just a basic—it’s a bold expression of individuality.
        '
    WHERE id = 2;

--- Levis 501

UPDATE product 
    SET longdescription =
        'Levi’s® 501® Original Fit Jeans – The Icon That Started It All
        Born in 1873 as the world’s first blue jeans, the Levi’s® 501® Original Fit is a timeless symbol of authenticity, rebellion, and American heritage. Crafted from premium heavyweight denim, these jeans feature a straight-leg silhouette with a classic mid-rise waist and a button-fly closure—staying true to their original workwear roots. The sturdy 100% cotton construction (with select stretch options for added comfort) molds to your body over time, creating a personalized fit that’s uniquely yours.
        The 501’s signature details—like the iconic red tab, leather-like patch, and reinforced rivets—pay homage to its durable legacy. Versatile enough to dress up with a blazer or keep casual with a vintage tee, they’re a staple in every denim lover’s wardrobe. Whether you prefer a rigid, unwashed look that fades beautifully with wear or a pre-washed, lived-in feel, the 501 adapts to your lifestyle while maintaining its rugged charm.
        From cowboys to rockstars, rebels to trendsetters, generations have made the 501 their own. More than just jeans—they’re a cultural icon. Fit note: True to size with a roomy thigh and straight leg opening for a classic, comfortable silhouette.'
WHERE id = 3;


INSERT INTO product_variant (id, product_id, attributes, upc)
    VALUES
        (1, 1, '{"color": "light blue", "size": "M"}', '123456789015'),
        (2, 1, '{"color": "white", "size": "L"}', '123456789016'),
        (3, 3, '{"color": "stonewash", "size": "32x32"}', '123456789017')
    ON CONFLICT (upc) DO NOTHING;

INSERT INTO product_variant_price (id, product_variant_id, price, currency, geography, validity, current)
    VALUES
        (1, 1, 31.00, 'EURO', 'EU', '[2025-06-01,)', true),
        (2, 1, 29.75, 'EURO', 'EU', '[2025-01-01, 2025-06-01)', false),
        (3, 1, 33.50, 'USD', 'US', '[2025-01-01, 2025-06-01)', false),
        (4, 1, 35.00, 'USD', 'US', '[2025-06-01,)', true)
    ON CONFLICT (id) DO NOTHING;


-- =================================================================
--  SECTION 5: STORED PROCEDURES AND MAINTENANCE QUERIES
-- =================================================================

\echo '--> Creating stored procedures for data maintenance...'

-- [IMPROVEMENT] Rewritten procedure to be more efficient.
CREATE OR REPLACE PROCEDURE update_current_price_flags()
    LANGUAGE SQL
    AS $$
    -- This single UPDATE is more efficient than iterating.
    -- It sets 'current' to true if the current date falls within the
    -- validity range, and false otherwise.
    UPDATE product_variant_price
    SET current = (validity @> current_date);
$$;

\echo '--> Example maintenance queries:'
\echo '    1. To run the procedure to update all flags: CALL update_current_price_flags();'
\echo '    2. To find products/variants without a current valid price:'

-- [IMPROVEMENT] Query to find variants without a current price.
SELECT
    v.id AS variant_id,
    v.upc,
    p.label AS product_label
FROM
    product_variant v
JOIN
    product p ON v.product_id = p.id
WHERE NOT EXISTS (
    SELECT 1
    FROM product_variant_price pvp
    WHERE pvp.product_variant_id = v.id AND pvp.current = true
);

\echo '*** Script Finished Successfully ***'
