-- =================================================================
--  PSQL SCRIPT FOR US E-COMMERCE SUBSCRIBER DATABASE
-- =================================================================
--  OWNER: Superuser
--  PURPOSE: Creates the database schema for the US-specific site.
--           Some tables are populated via logical replication.
-- =================================================================

-- =================================================================
--  SECTION 1: DATABASE PREPARATION
-- =================================================================
-- Note: Run this script while connected to a neutral DB (e.g., 'postgres').

\echo '[DATABASE PREP] ==> Preparing to drop and recreate the database.'

-- Terminate active connections before dropping the database for a safe teardown.
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = 'us_ecommerce_data' AND pid <> pg_backend_pid();

DROP DATABASE IF EXISTS us_ecommerce_data;

\echo '[DATABASE PREP] ==> Creating the database...'
CREATE DATABASE us_ecommerce_data;

-- Switch connection to the newly created database.
\c us_ecommerce_data
\echo '--> Successfully connected to database: us_ecommerce_data'

-- =================================================================
--  SECTION 2: EXTENSIONS & REPLICATED TABLE STRUCTURES
-- =================================================================
-- These tables will be populated by logical replication from the
-- 'ecommerce_reference_data' database. Their structure must match
-- the publisher's definition exactly. Do NOT insert data manually.
-- =================================================================

\echo '--> Creating extensions...'
CREATE EXTENSION IF NOT EXISTS btree_gist;

\echo '--> Creating schemas for REPLICATED tables...'
CREATE TABLE product_category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product_brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_category_id INTEGER NOT NULL REFERENCES product_category (id),
    product_brand_id INTEGER NOT NULL REFERENCES product_brand (id),
    label VARCHAR(50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50)
);

CREATE TABLE product_variant (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product(id),
    attributes JSONB,
    upc VARCHAR(12) UNIQUE NOT NULL
);

CREATE TABLE product_variant_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant_id INTEGER NOT NULL REFERENCES product_variant(id),
    price NUMERIC(10, 2) NOT NULL,
    currency VARCHAR(4) NOT NULL, -- Matched to publisher's ENUM type as VARCHAR
    geography VARCHAR(3) NOT NULL,
    validity DATERANGE NOT NULL,
    current BOOLEAN NOT NULL DEFAULT false
);

-- =================================================================
--  SECTION 3: LOCAL TABLE DEFINITIONS
-- =================================================================
-- These tables exist only on the US database and are not replicated.
-- =================================================================

\echo '--> Creating schemas for LOCAL tables...'

-- Simplified inventory model
CREATE TABLE product_variant_inventory (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant_id INTEGER NOT NULL REFERENCES product_variant(id) ON DELETE CASCADE,
    qty INTEGER NOT NULL DEFAULT 0 CHECK (qty >= 0),
    CONSTRAINT uq_inventory_variant UNIQUE (product_variant_id)
);

-- Simplified customer model
CREATE TABLE customer (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone_numbers JSONB,
    street_address VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(50) NOT NULL
);

-- Sales transaction header
CREATE TABLE sales_transaction (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id INTEGER NOT NULL REFERENCES customer(id)
);

-- Sales transaction line items
CREATE TABLE sales_transaction_line (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sales_transaction_id UUID NOT NULL REFERENCES sales_transaction(id) ON DELETE CASCADE,
    product_variant_id INTEGER NOT NULL REFERENCES product_variant(id),
    qty INTEGER NOT NULL CHECK (qty > 0),
    price_at_sale NUMERIC(10, 2) NOT NULL CHECK (price_at_sale >= 0)
);

-- =================================================================
--  SECTION 4: SAMPLE DATA AND PROCEDURES (COMMENTED OUT)
-- =================================================================
-- The following blocks are for populating the LOCAL tables with
-- sample data after replication has been established and the
-- replicated tables contain data.
-- =================================================================
/*
\echo '--> Inserting sample data for local tables...'

INSERT INTO product_variant_inventory (product_variant_id, qty)
    VALUES
        (1, 100),
        (2, 12),
        (3, 59)
    ON CONFLICT (product_variant_id) DO UPDATE SET qty = EXCLUDED.qty;

INSERT INTO customer (id, first_name, last_name, phone_numbers, street_address, city, postal_code, country)
    VALUES
        (1, 'Marc', 'Linster', '{"mobile": "+1-617-555-0101"}', '10 Main St', 'Boston', 'MA 02101', 'USA'),
        (2, 'Vibhor', 'Kumar', '{"mobile": "+1-781-555-0102"}', '250 First Ave', 'Needham', 'MA 02494', 'USA')
    ON CONFLICT (id) DO NOTHING;

-- [IMPROVEMENT] This procedure is heavily optimized for performance and correctness.
CREATE OR REPLACE PROCEDURE create_sales_transactions(num_transactions INTEGER)
LANGUAGE PLPGSQL AS $$
DECLARE
    -- Variables for transaction header
    new_transaction_id UUID;
    random_customer_id INTEGER;
    random_date DATE;
    -- Variables for transaction lines
    num_lines INTEGER;
    random_variant_id INTEGER;
    current_price NUMERIC;
    random_qty INTEGER;
BEGIN
    -- Get the range of available IDs for customers and variants to avoid slow queries
    FOR i IN 1..num_transactions LOOP
        -- 1. Create the Sales Transaction Header
        SELECT id INTO random_customer_id FROM customer ORDER BY random() LIMIT 1;
        random_date := current_date - (random() * 365)::INTEGER;

        INSERT INTO sales_transaction (transaction_date, customer_id)
        VALUES (random_date, random_customer_id)
        RETURNING id INTO new_transaction_id;

        -- 2. Create Sales Transaction Lines
        num_lines := floor(random() * 5 + 1); -- 1 to 5 lines
        FOR j IN 1..num_lines LOOP
            -- Get a random product variant
            SELECT id INTO random_variant_id FROM product_variant ORDER BY random() LIMIT 1;

            -- CORRECTLY get the CURRENT price for the US region
            SELECT price INTO current_price
            FROM product_variant_price
            WHERE product_variant_id = random_variant_id
              AND geography = 'US'
              AND current = true
            LIMIT 1;

            -- Only insert a line if a valid price was found
            IF FOUND THEN
                random_qty := floor(random() * 3 + 1); -- 1 to 3 items

                INSERT INTO sales_transaction_line (sales_transaction_id, product_variant_id, qty, price_at_sale)
                VALUES (new_transaction_id, random_variant_id, random_qty, current_price);
            END IF;
        END LOOP;
    END LOOP;
END $$;

\echo '--> To generate sample transactions, run: CALL create_sales_transactions(10);'
*/
