-- =================================================================
--  PSQL SCRIPT FOR AI Database
-- =================================================================
--  OWNER: Superuser
--  PURPOSE: Creates the database schema for the AIDB database,
--           including product reference data and embedding tables.
-- =================================================================

-- =================================================================
--  SECTION 1: SCHEMA PREPARATION
-- =================================================================
-- =================================================================
--  PSQL SCRIPT FOR E-COMMERCE REFERENCE DATA SETUP
-- =================================================================
--  OWNER: Superuser
--  PURPOSE: Creates the database schema, tables
--           for product reference information.
-- =================================================================

-- =================================================================
--  SECTION 1: SCHEMA PREPARATION
-- =================================================================
\c aidb
\echo '--> Successfully connected to database: aidb'

CREATE EXTENSION IF NOT EXISTS vector;       -- pgvector
CREATE EXTENSION IF NOT EXISTS plpython3u;   -- demo only (untrusted; needs superuser)

\echo '--> Creating the schemata for api, product_refence, inventory, customer, and sales data'

CREATE SCHEMA IF NOT EXISTS api;
CREATE SCHEMA IF NOT EXISTS product; -- replicated to us/eu_aidb.product.*
CREATE SCHEMA IF NOT EXISTS internal;
CREATE SCHEMA IF NOT EXISTS embeddings;

\echo '--> Creating the search path at the database level'

ALTER DATABASE aidb SET SEARCH_PATH TO api, product, internal, public; -- permanent change
SET SEARCH_PATH TO api, product, internal, embeddings, public; --- make sure path is available in current session

-- =================================================================
--  SECTION 2: EXTENSIONS AND CUSTOM TYPES
-- =================================================================

\echo '--> Creating extensions...'
-- btree_gist is required for using the GIST exclusion constraint on a DATERANGE.
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS vector;       -- pgvector
CREATE EXTENSION IF NOT EXISTS plpython3u;   -- demo only (untrusted; needs superuser)

\echo '--> Creating custom ENUM types...'
-- Using ENUMs helps ensure data integrity for controlled vocabularies.
CREATE TYPE internal.sales_geo AS ENUM ('East', 'West');


-- =================================================================
--  SECTION 3: TABLE DEFINITIONS
-- =================================================================

\echo '--> Creating product tables...'

CREATE TABLE product.category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product.brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product.country_of_origin (
    brand_id INTEGER PRIMARY KEY REFERENCES brand (id),
    --- three digit ISO 3166-1 A-3
    alpha3_code VARCHAR(3) NOT NULL,
    name TEXT
);

CREATE TABLE product.product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id INTEGER NOT NULL REFERENCES product.category (id),
    brand_id INTEGER NOT NULL REFERENCES product.brand (id),
    label VARCHAR (50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50)
);

CREATE TABLE product.product_variant (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product.product(id) ON DELETE CASCADE,
    attributes JSONB
);

CREATE TABLE product.product_variant_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant_id INTEGER NOT NULL REFERENCES product.product_variant (id) ON DELETE CASCADE,
    -- make sure the prices are always greater 0
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    -- DATERANGE where the lower bound is inclusive, and the upper bound is exclusive.
    validity DATERANGE NOT NULL,
    current BOOLEAN NOT NULL DEFAULT false,
    -- Ensures that there are no overlapping price validity periods for the same product and geography.
    EXCLUDE USING GIST (product_variant_id WITH =, validity WITH &&)
);

ALTER TABLE product.product_variant_price REPLICA IDENTITY FULL;

-- =================================================================
--  SECTION 4: EMBEDDINGS DATA
-- =================================================================
-- These tables store vector embeddings for various entities to
-- support semantic search and other AI-powered features.
-- The embedding dimension is set to 1536, a common size for models
-- like OpenAI's text-embedding-ada-002.
-- =================================================================

\echo '--> Creating embedding tables'

-- Embeddings for product categories.
-- The embedding should be generated from the 'label' and 'description' fields.
CREATE TABLE embeddings.product_category_embedding (
    product_category_id INTEGER PRIMARY KEY REFERENCES product.category(id) ON DELETE CASCADE,
    embedding VECTOR(1536) NOT NULL
);

-- Embeddings for product brands.
-- The embedding should be generated from the 'label' and 'description' fields.
CREATE TABLE embeddings.product_brand_embedding (
    product_brand_id INTEGER PRIMARY KEY REFERENCES product.brand(id) ON DELETE CASCADE,
    embedding VECTOR(1536) NOT NULL
);

-- Embeddings for products.
-- The embedding should be generated from 'label', 'shortdescription', and 'longdescription'.
CREATE TABLE embeddings.product_embedding (
    product_id INTEGER PRIMARY KEY REFERENCES product.product(id) ON DELETE CASCADE,
    embedding VECTOR(1536) NOT NULL
);

-- Embeddings for product variants.
-- The embedding should be generated from the 'attributes' JSONB field.
CREATE TABLE embeddings.product_variant_embedding (
    product_variant_id INTEGER PRIMARY KEY REFERENCES product.product_variant(id) ON DELETE CASCADE,
    embedding VECTOR(1536) NOT NULL
);


-- --- Embedding helpers (OpenAI) -------------------------------------------
-- Store API key/org in session-scoped DB GUCs:
--   SELECT set_config('api.openai_api_key','sk-...YOUR_KEY...', false);
--   SELECT set_config('api.openai_organization','org_...optional...', false);

-- Single-text embedding with retries/backoff
CREATE OR REPLACE FUNCTION api.openai_embed(input_text text)
RETURNS float4[]
LANGUAGE plpython3u
AS $$
import json, ssl, time, random, urllib.request, urllib.error
def call_openai(payload, api_key, org):
    req = urllib.request.Request(
        "https://api.openai.com/v1/embeddings",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
            **({"OpenAI-Organization": org} if org else {})
        }
    )
    ctx = ssl.create_default_context()
    with urllib.request.urlopen(req, context=ctx, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))

rv = plpy.execute("SELECT current_setting('api.openai_api_key', true) AS k, current_setting('api.openai_organization', true) AS o")
api_key = rv[0]["k"] if rv and rv[0]["k"] is not None else None
org     = rv[0]["o"] if rv and rv[0]["o"] is not None else None
if not api_key:
    raise Exception("OpenAI API key not set. Use: SELECT set_config('api.openai_api_key','sk-...','f');")

payload = {"model":"text-embedding-3-small","input": input_text or ""}

attempts = 6
for i in range(attempts):
    try:
        data = call_openai(payload, api_key, org)
        emb = data["data"][0]["embedding"]
        return [float(x) for x in emb]
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="ignore")
        if e.code not in (429, 500, 502, 503, 504) or i == attempts - 1:
            raise Exception(f"OpenAI HTTP {e.code}. Body: {body[:400]} ...")
        time.sleep((2 ** i) * 0.5 + random.uniform(0, 0.3))
    except Exception as e:
        if i == attempts - 1:
            raise
        time.sleep((2 ** i) * 0.5 + random.uniform(0, 0.2))
$$;

-- Batch embeddings (array of texts)
CREATE OR REPLACE FUNCTION api.openai_embed_batch(inputs text[])
RETURNS float4[][]
LANGUAGE plpython3u
AS $$
import json, ssl, time, random, urllib.request, urllib.error
def call_openai(payload, api_key, org):
    req = urllib.request.Request(
        "https://api.openai.com/v1/embeddings",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
            **({"OpenAI-Organization": org} if org else {})
        }
    )
    ctx = ssl.create_default_context()
    with urllib.request.urlopen(req, context=ctx, timeout=60) as resp:
        return json.loads(resp.read().decode("utf-8"))

rv = plpy.execute("SELECT current_setting('api.openai_api_key', true) AS k, current_setting('api.openai_organization', true) AS o")
api_key = rv[0]["k"] if rv and rv[0]["k"] is not None else None
org     = rv[0]["o"] if rv and rv[0]["o"] is not None else None
if not api_key:
    raise Exception("OpenAI API key not set. Use: SELECT set_config('api.openai_api_key','sk-...','f');")

items = [i if i is not None else "" for i in (inputs or [])]
if not items:
    return []

payload = {"model":"text-embedding-3-small","input": items}

attempts = 6
for i in range(attempts):
    try:
        data = call_openai(payload, api_key, org)
        out = []
        for d in data["data"]:
            out.append([float(x) for x in d["embedding"]])
        return out
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="ignore")
        if e.code not in (429, 500, 502, 503, 504) or i == attempts - 1:
            raise Exception(f"OpenAI HTTP {e.code}. Body: {body[:400]} ...")
        time.sleep((2 ** i) * 0.5 + random.uniform(0, 0.3))
    except Exception as e:
        if i == attempts - 1:
            raise
        time.sleep((2 ** i) * 0.5 + random.uniform(0, 0.2))
$$;

CREATE INDEX IF NOT EXISTS product_embedding_ivfflat_idx
  ON embeddings.product_embedding USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
ANALYZE embeddings.product_embedding;

-- Embed products in small batches using batch API
-- SIMPLE & RELIABLE: per-row embedding (no array gymnastics)
CREATE OR REPLACE FUNCTION api.embed_products(batch_size int DEFAULT 200)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
    r RECORD;
    done_count int := 0;
BEGIN
    FOR r IN
        SELECT p.id, p.label, p.shortdescription, p.longdescription,
               pc.label AS category_label,
               pb.label AS brand_label
        FROM product.product p
        JOIN product.category pc ON pc.id = p.category_id
        JOIN product.brand    pb ON pb.id = p.brand_id
        LEFT JOIN embeddings.product_embedding pe ON pe.product_id = p.id
        WHERE pe.product_id IS NULL
        ORDER BY p.id
        LIMIT batch_size
    LOOP
        BEGIN
            -- Use MERGE to prevent race conditions. If another process embeds
            -- this product after the initial SELECT, this command will safely
            -- do nothing instead of raising a unique key violation error.
            MERGE INTO embeddings.product_embedding AS target
            USING (SELECT r.id AS product_id) AS source
            ON (target.product_id = source.product_id)
            WHEN NOT MATCHED THEN
              INSERT (product_id, embedding)
              VALUES (r.id, api.openai_embed(
                  coalesce(r.label, '') || ' ' ||
                  coalesce(r.brand_label, '') || ' ' ||
                  coalesce(r.category_label, '') || ' ' ||
                  coalesce(r.shortdescription, '') || ' ' ||
                  coalesce(r.longdescription, '')));
            done_count := done_count + 1;
        EXCEPTION WHEN OTHERS THEN
            RAISE NOTICE 'Failed to embed product id %: %', r.id, SQLERRM;
        END;
    END LOOP;

    RETURN done_count;
END;
$$;

COMMENT ON FUNCTION api.embed_products(int) IS 'Embeds up to batch_size products lacking vectors; returns count updated.';

-- --- Pairing view (item->item within complementary categories) ------------
CREATE OR REPLACE VIEW api.product_pairs_demo AS
SELECT
  p1.id    AS base_product_id,
  p1.label AS base_name,
  c1.label AS base_category,
  p2.id    AS candidate_product_id,
  p2.label AS candidate_name,
  c2.label AS candidate_category,
  (pe1.embedding <=> pe2.embedding)::double precision AS cosine_distance
FROM product.product p1
JOIN embeddings.product_embedding pe1 ON p1.id = pe1.product_id
JOIN product.category c1 ON c1.id = p1.category_id
-- The api.category_complements table is not defined in this script.
-- Assuming it exists and has columns 'category_name' and 'complements' (text[]).
-- JOIN api.category_complements cc ON cc.category_name = c1.label
JOIN product.product p2 ON p2.id <> p1.id
JOIN embeddings.product_embedding pe2 ON p2.id = pe2.product_id
JOIN product.category c2 ON c2.id = p2.category_id
-- WHERE c2.label = ANY (cc.complements);
WHERE c1.id <> c2.id; -- Simplified logic: show pairs from different categories

-- --- Similar-items (query embedding once; returns double precision) --------
CREATE OR REPLACE FUNCTION api.similar_items(query_text text, k int DEFAULT 10)
RETURNS TABLE(product_id int, name text, category text, shortdescription text, longdescription text, price numeric, distance double precision)
LANGUAGE plpgsql
AS $$
DECLARE
    qvec vector(1536);
BEGIN
    SELECT api.openai_embed(query_text)::vector(1536) INTO qvec;
    RETURN QUERY
    WITH RES AS MATERIALIZED (
      SELECT
          p.id                    AS product_id,
          p.label::text           AS name,
          c.label::text           AS category,
          p.shortdescription::text AS shortdescription,
          p.longdescription::text  AS longdescription,
          pvp.price               AS price,
          (qvec <=> pe.embedding) AS distance
      FROM product.product p
      JOIN embeddings.product_embedding pe ON p.id = pe.product_id
      JOIN product.category c ON c.id = p.category_id
      JOIN product.product_variant pv ON pv.product_id = p.id
      JOIN product.product_variant_price pvp ON pvp.product_variant_id = pv.id AND pvp.current = true
    ORDER BY pe.embedding <=> qvec)
    SELECT * FROM RES
    LIMIT k;
END;
$$;

-- Answer a question using OpenAI - Humanize results with OpenAI
CREATE OR REPLACE FUNCTION api.answer_with_openai(p_question text, p_rows jsonb)
RETURNS text
LANGUAGE plpython3u
AS $$
import json, ssl, urllib.request

rows = json.dumps(p_rows)

rv = plpy.execute("SELECT current_setting('api.openai_api_key', true) AS k")
api_key = rv[0]["k"] if rv and rv[0]["k"] is not None else None
if not api_key:
    raise Exception("OpenAI API key not set.")

SYSTEM = """You are a helpful assistant.
Take the user question and the SQL rows returned, and write a clear, human reply.
- Mention the question.
- Summarize how many results were found.
- List items with their label, price if present, and category.
- Do not invent anything beyond rows JSON.
Schema tables/columns:
- product.product(id, category_id, brand_id, label, shortdescription, longdescription)
- embeddings.product_embedding(product_id, embedding)
- product.category(id, label, description)
- product.brand(id, label, description)
- product.product_variant(id, product_id, attributes)
- product.product_variant_price(id, product_variant_id, price, validity, current)
- api.category_complements(category_name, complements)

Rules:
- Categories are broad: product.category.label values like 'Jeans', 'Shirt', 'Skirt'.
- Gender words (women, men, kids) appear in product.label, NOT in category.
- Price: product_variant_price.price (alias pvp).
- Color/size attributes are in product_variant.attributes (JSONB).
- Category: product.category.label (alias pc). Join pc ON pc.id = p.category_id.
- To use price/color: JOIN product_variant pv ON pv.product_id = p.id
  AND JOIN product_variant_price pvp ON pvp.product_variant_id = pv.id.
- Use LOWER() for case-insensitive filters, e.g. LOWER(p.name) LIKE '%women%'.
- Only SELECT. No semicolons. Always LIMIT {row_limit}.
- Prefer clear aliases (product_name, price).
- If no rows are returned just respond.
"""

USER = f"Question: {p_question}\n\nRows: {rows}"

payload = {
  "model": "gpt-4o-mini",
  "messages": [
    {"role":"system","content":SYSTEM},
    {"role":"user","content":USER}
  ],
  "temperature": 0.2,
  "max_tokens": 500
}

headers = {"Content-Type":"application/json","Authorization":f"Bearer {api_key}"}
ctx = ssl.create_default_context()
req = urllib.request.Request("https://api.openai.com/v1/chat/completions",
                             data=json.dumps(payload).encode("utf-8"),
                             headers=headers)
with urllib.request.urlopen(req, context=ctx) as resp:
    data = json.loads(resp.read().decode("utf-8"))
return data["choices"][0]["message"]["content"].strip()
$$;


-- Answer a question using OpenAI - Humanize results with OpenAI and returns results

CREATE OR REPLACE FUNCTION api.chat(p_question text, k int DEFAULT 10)
RETURNS TABLE(assistant_text text, rows jsonb)
LANGUAGE plpgsql
AS $$
DECLARE
  data jsonb;
BEGIN
  SELECT jsonb_agg(t) INTO data
  FROM (
    SELECT s.product_id, s.name, s.category, s.shortdescription, s.longdescription, s.price, s.distance
    FROM api.similar_items(p_question, k) s
  ) t;

  assistant_text := api.answer_with_openai(p_question, data);
  rows := coalesce(data, '[]'::jsonb);

  RETURN NEXT;
END;
$$;


/*
 =============================================================================
 Quick use
 =============================================================================
 1) Set your API key (session-only):
    SELECT set_config('api.openai_api_key','sk-...YOUR_KEY...', false);

 2) Create some embeddings (run a few times if you have more rows):
    SELECT api.embed_products(25);

 3) Similar-items demo using embeddings:
    SELECT * FROM api.similar_items('Show me premium men''s clothes', 2);

 4) Chat with the assistant:
    SELECT * FROM api.chat('What are some similar items?', 2);
    SELECT * FROM api.chat('looking for tailored clothing', 5);
    SELECT * FROM api.chat('Tell me about polo shirts in different colors', 3);
    SELECT * FROM api.chat('What are the best pants for men?', 4);

*/
