/* 
================================================================================
  PSQL SCRIPT FOR CENTRAL ANALYTICS DATABASE
================================================================================
  OWNER: Superuser
  PURPOSE: Creates the database schema for central analytics.
           All tables are populated via logical replication.
           All data is read only
  Schemas:
           * api has views to access the data for reporting
             * product has product and pricing data
           * product provides definitions for 
             products and prices into schema product
           * east_customer holds the customer table replicated from the 
             east_ecommerce_data database
           * west_customer holds the customer table replicated from the
             west_ecommerce_data database
           * customer_merged holds the customer table that assembles 
             the west and east customer data, but filters out PII
           * east_sales holds the east sales transactions and sales transaction lines
           * west_sales holds the west sales transactions and sales transaction lines 
           * sales_merged holds the sales_transaction and 
             sales_transaction_lines tables that assembles the east and west
             data
            
================================================================================

================================================================================
  SECTION 1: SCHEMA PREPARATION
 =================================================================
*/

-- Switch connection to the database.
\c central_analytics

CREATE SCHEMA api;
CREATE SCHEMA product;
CREATE SCHEMA customer;
CREATE SCHEMA east_sales;
CREATE SCHEMA west_sales;
CREATE SCHEMA merged_sales;

\echo '--> Creating the search path at the database level'

ALTER DATABASE central_analytics SET SEARCH_PATH TO api, product, customer, merged_sales; -- permanent change
SET SEARCH_PATH TO api, product, customer, merged_sales;  --- make sure path is available in current session

-- =================================================================
--  SECTION 2: PRODUCT REFERENCE DATA
-- =================================================================
-- These tables will be populated by logical replication from the
-- 'ecommerce_reference_data' database. Their structure must match
-- the publisher's definition exactly. Do NOT insert data manually.
-- =================================================================


CREATE TABLE product.category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product.brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product.country_of_origin (
    brand_id INTEGER PRIMARY KEY REFERENCES brand (id),
    --- three digit ISO 3166-1 A-3
    alpha3_code VARCHAR(3) NOT NULL,
    name TEXT
);

CREATE TABLE product.product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id INTEGER NOT NULL REFERENCES product.category (id),
    brand_id INTEGER NOT NULL REFERENCES product.brand (id),
    label VARCHAR(50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50)
);

CREATE TABLE product.product_variant (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product.product(id) ON DELETE CASCADE,
    attributes JSONB
);


CREATE TABLE product.product_variant_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant_id INTEGER NOT NULL REFERENCES product.product_variant (id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    -- DATERANGE where the lower bound is inclusive, and the upper bound is exclusive.
    validity DATERANGE NOT NULL,
    current BOOLEAN NOT NULL DEFAULT false
);

-- =================================================================
--  SECTION 2: CUSTOMER DATA
-- =================================================================



-- merged customer data data from the east and west

CREATE TABLE customer.customer (
    id UUID PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone_numbers JSONB,
    street_address VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(50) NOT NULL,
    origin VARCHAR(4) NOT NULL
);


-- =================================================================
--  SECTION 2: SALES DATA
-- =================================================================

-- replicated data from the west ecommerce site
-- add an origin column to be able to use it as a partion

CREATE TABLE west_sales.sales_transaction (
    id UUID UNIQUE NOT NULL, -- needs to be unique to support foreign key
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id UUID,
    origin VARCHAR(4) NOT NULL DEFAULT 'WEST'
);

CREATE TABLE west_sales.sales_transaction_line (
    id UUID NOT NULL,
    sales_transaction_id UUID NOT NULL REFERENCES west_sales.sales_transaction(id) ON DELETE CASCADE,
    product_variant_id INTEGER NOT NULL,
    qty INTEGER,
    price_at_sale NUMERIC(10, 2),
    origin VARCHAR(4) NOT NULL DEFAULT 'WEST'
);

-- replicated data from the EU
-- add an origin column to be able to use it as a partion

CREATE TABLE east_sales.sales_transaction (
    id UUID UNIQUE NOT NULL, -- needs to be unique to support foreign key
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id UUID,
    origin VARCHAR(4) NOT NULL DEFAULT 'EAST'
);

CREATE TABLE east_sales.sales_transaction_line (
    id UUID NOT NULL,
    sales_transaction_id UUID NOT NULL REFERENCES east_sales.sales_transaction(id) ON DELETE CASCADE,
    product_variant_id INTEGER NOT NULL,
    qty INTEGER,
    price_at_sale NUMERIC(10, 2),
    origin VARCHAR(4) NOT NULL DEFAULT 'EAST'
);


-- merged sales data

CREATE TABLE merged_sales.sales_transaction(
    id UUID,
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id UUID,
    origin VARCHAR(4),
    PRIMARY KEY (id, origin),
    FOREIGN KEY (customer_id) REFERENCES customer.customer (id)
) PARTITION BY LIST (origin);

ALTER TABLE merged_sales.sales_transaction ATTACH PARTITION east_sales.sales_transaction FOR VALUES IN ('EAST');
ALTER TABLE merged_sales.sales_transaction ATTACH PARTITION west_sales.sales_transaction FOR VALUES IN ('WEST');


CREATE TABLE merged_sales.sales_transaction_line (
    id UUID,
    sales_transaction_id UUID,
    product_variant_id INTEGER NOT NULL,
    qty INTEGER,
    price_at_sale NUMERIC(10, 2),
    origin VARCHAR(4),
    PRIMARY KEY (id, origin),
    FOREIGN KEY (sales_transaction_id, origin) REFERENCES merged_sales.sales_transaction (id, origin),
    FOREIGN KEY (product_variant_id) REFERENCES product.product_variant (id)
) PARTITION BY LIST (origin);

ALTER TABLE merged_sales.sales_transaction_line ATTACH PARTITION east_sales.sales_transaction_line FOR VALUES IN ('EAST');
ALTER TABLE merged_sales.sales_transaction_line ATTACH PARTITION west_sales.sales_transaction_line FOR VALUES IN ('WEST');


/******************************************************************************
    Logic to delete PII from the customer data after replication to 
    to central analytics.
    PII: first_name, last_name, street_address, phone_numbers
    PII is deleted upon INSERT and UPDATE
******************************************************************************/

CREATE OR REPLACE FUNCTION api.sf_delete_PII_from_customer () 
RETURNS TRIGGER AS
$$
  BEGIN
    NEW.first_name = 'masked';
    NEW.last_name = 'masked';
    NEW.phone_numbers = '{"home": "+1 (555) 123-345", "mobile": "+1 (555) 456-789"}';
    RETURN NEW;
  END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER tr_delete_PII_from_customer 
  BEFORE INSERT OR UPDATE
  ON customer.customer FOR EACH ROW EXECUTE FUNCTION api.sf_delete_PII_from_customer();

ALTER TABLE customer.customer ENABLE REPLICA TRIGGER tr_delete_PII_from_customer;

