/* 
================================================================================
  PSQL SCRIPT FOR CENTRAL ANALYTICS DATABASE
================================================================================
  OWNER: Superuser
  PURPOSE: Creates the database schema for central analytics.
           All tables are populated via logical replication.
           All data is read only
  Schemas:
           * api has views to access the data for reporting
             * product_reference has product and pricing data
           * product_reference provides definitions for 
             products and prices into schema product_reference
           * east_customer holds the customer table replicated from the 
             east_ecommerce_data database
           * west_customer holds the customer table replicated from the
             west_ecommerce_data database
           * customer_merged holds the customer table that assembles 
             the west and east customer data, but filters out PII
           * east_sales holds the east sales transactions and sales transaction lines
           * west_sales holds the west sales transactions and sales transaction lines 
           * sales_merged holds the sales_transaction and 
             sales_transaction_lines tables that assembles the east and west
             data
            
================================================================================

================================================================================
  SECTION 1: DATABASE PREPARATION
 =================================================================
 Note: Run this script while connected to a neutral DB (e.g., 'postgres').
*/

\echo '[DATABASE PREP] ==> Preparing to drop and recreate the database.'
-- Terminate all active connections to the target database before dropping it.
-- This is a more controlled approach than using WITH (FORCE).
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = 'central_analytics' AND pid <> pg_backend_pid();

DROP DATABASE IF EXISTS central_analytics;

\echo '[DATABASE PREP] ==> Creating the database...'
CREATE DATABASE central_analytics;

-- Switch connection to the newly created database.
\c central_analytics

CREATE SCHEMA api;
CREATE SCHEMA product_reference;
CREATE SCHEMA east_customer;
CREATE SCHEMA west_customer;
CREATE SCHEMA merged_customer;
CREATE SCHEMA east_sales;
CREATE SCHEMA west_sales;
CREATE SCHEMA merged_sales;

\echo '--> Creating the search path at the database level'

ALTER DATABASE central_analytics SET SEARCH_PATH TO api, product_reference, customer_merged, sales_merged; -- permanent change
SET SEARCH_PATH TO api, product_reference, customer_merged, sales_merged;  --- make sure path is available in current session

-- =================================================================
--  SECTION 2: PRODUCT REFERENCE DATA
-- =================================================================
-- These tables will be populated by logical replication from the
-- 'ecommerce_reference_data' database. Their structure must match
-- the publisher's definition exactly. Do NOT insert data manually.
-- =================================================================


CREATE TABLE product_reference.product_category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product_reference.product_brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product_reference.product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_category_id INTEGER NOT NULL REFERENCES product_reference.product_category (id),
    product_brand_id INTEGER NOT NULL REFERENCES product_reference.product_brand (id),
    label VARCHAR(50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50)
);


CREATE TABLE product_reference.product_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product_reference.product (id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    -- DATERANGE where the lower bound is inclusive, and the upper bound is exclusive.
    validity DATERANGE NOT NULL,
    current BOOLEAN NOT NULL DEFAULT false
);

-- =================================================================
--  SECTION 2: CUSTOMER DATA
-- =================================================================

-- replicated data from the west ecommerce

CREATE TABLE west_customer.customer (
    id TEXT NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone_numbers JSONB,
    street_address VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(50) NOT NULL,
    origin VARCHAR(4) NOT NULL DEFAULT 'WEST'
);

-- replicated data from the EU

CREATE TABLE east_customer.customer (
    id TEXT NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone_numbers JSONB,
    street_address VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(50) NOT NULL,
    origin VARCHAR(4) NOT NULL DEFAULT 'EAST'
);


-- merged customer data data from the east and west

CREATE TABLE merged_customer.customer (
    id TEXT,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone_numbers JSONB,
    street_address VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(50) NOT NULL,
    origin VARCHAR(4) NOT NULL,
    PRIMARY KEY (id, origin)
)
PARTITION BY LIST (origin);


ALTER TABLE merged_customer.customer ATTACH PARTITION east_customer.customer FOR VALUES IN ('EAST');
ALTER TABLE merged_customer.customer ATTACH PARTITION west_customer.customer FOR VALUES IN ('WEST');


-- =================================================================
--  SECTION 2: SALES DATA
-- =================================================================

-- replicated data from the west ecommerce site
-- add an origin column to be able to use it as a partion

CREATE TABLE west_sales.sales_transaction (
    id TEXT UNIQUE NOT NULL,
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id TEXT,
    origin VARCHAR(4) NOT NULL DEFAULT 'WEST'
);

CREATE TABLE west_sales.sales_transaction_line (
    id TEXT UNIQUE NOT NULL,
    sales_transaction_id TEXT NOT NULL REFERENCES west_sales.sales_transaction(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL,
    qty INTEGER,
    price_at_sale NUMERIC(10, 2),
    origin VARCHAR(4) NOT NULL DEFAULT 'WEST'
);

-- replicated data from the EU
-- add an origin column to be able to use it as a partion

CREATE TABLE east_sales.sales_transaction (
    id TEXT UNIQUE NOT NULL,
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id TEXT,
    origin VARCHAR(4) NOT NULL DEFAULT 'EAST'
);

CREATE TABLE east_sales.sales_transaction_line (
    id TEXT UNIQUE NOT NULL,
    sales_transaction_id TEXT NOT NULL REFERENCES east_sales.sales_transaction(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL,
    qty INTEGER,
    price_at_sale NUMERIC(10, 2),
    origin VARCHAR(4) NOT NULL DEFAULT 'EAST'
);


-- merged sales data

CREATE TABLE merged_sales.sales_transaction(
    id TEXT,
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id TEXT,
    origin VARCHAR(4),
    PRIMARY KEY (id, origin),
    FOREIGN KEY (customer_id, origin) REFERENCES merged_customer.customer (id, origin)
) PARTITION BY LIST (origin);

ALTER TABLE merged_sales.sales_transaction ATTACH PARTITION east_sales.sales_transaction FOR VALUES IN ('EAST');
ALTER TABLE merged_sales.sales_transaction ATTACH PARTITION west_sales.sales_transaction FOR VALUES IN ('WEST');


CREATE TABLE merged_sales.sales_transaction_line (
    id TEXT,
    sales_transaction_id TEXT,
    product_id INTEGER NOT NULL,
    qty INTEGER,
    price_at_sale NUMERIC(10, 2),
    origin VARCHAR(4),
    PRIMARY KEY (id, origin),
    FOREIGN KEY (sales_transaction_id, origin) REFERENCES merged_sales.sales_transaction (id, origin),
    FOREIGN KEY (product_id) REFERENCES product_reference.product (id)
) PARTITION BY LIST (origin);

ALTER TABLE merged_sales.sales_transaction_line ATTACH PARTITION east_sales.sales_transaction_line FOR VALUES IN ('EAST');
ALTER TABLE merged_sales.sales_transaction_line ATTACH PARTITION west_sales.sales_transaction_line FOR VALUES IN ('WEST');
