/* 
================================================================================
  PSQL SCRIPT FOR CENTRAL ANALYTICS DATABASE
================================================================================
  OWNER: Superuser
  PURPOSE: Creates the database schema for central analytics.
           All tables are populated via logical replication.
           All data is read only
  Schemas:
           * api has views to access the data for reporting
             * product has product and pricing data
           * product provides definitions for 
             products and prices into schema product
           * sales holds the customer table replicated from the 
             east_ecommerce_data and west_ecommerce_data databases
           * customer holds the customer table that assembles 
             the west and east customer data, but filters out PII            
================================================================================

================================================================================
  SECTION 1: SCHEMA PREPARATION
 =================================================================
*/

-- Switch connection to the database.
\c central_analytics

CREATE SCHEMA api;
CREATE SCHEMA product;
CREATE SCHEMA customer;
CREATE SCHEMA sales;

\echo '--> Creating the search path at the database level'

-- the analytics schema will be used for views and reporting
ALTER DATABASE central_analytics SET SEARCH_PATH TO api, product, customer, sales; -- permanent change
SET SEARCH_PATH TO api, product, customer, sales;  --- make sure path is available in current session

-- =================================================================
--  SECTION 2: PRODUCT REFERENCE DATA
-- =================================================================
-- These tables will be populated by logical replication from the
-- 'ecommerce_reference_data' database. Their structure must match
-- the publisher's definition exactly. Do NOT insert data manually.
-- =================================================================


CREATE TABLE product.category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product.brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product.country_of_origin (
    brand_id INTEGER PRIMARY KEY REFERENCES brand (id),
    --- three digit ISO 3166-1 A-3
    alpha3_code VARCHAR(3) NOT NULL,
    name TEXT
);

CREATE TABLE product.product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id INTEGER NOT NULL REFERENCES product.category (id),
    brand_id INTEGER NOT NULL REFERENCES product.brand (id),
    label VARCHAR(50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50)
);

CREATE TABLE product.product_variant (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product.product(id) ON DELETE CASCADE,
    attributes JSONB
);


CREATE TABLE product.product_variant_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant_id INTEGER NOT NULL REFERENCES product.product_variant (id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    -- DATERANGE where the lower bound is inclusive, and the upper bound is exclusive.
    validity DATERANGE NOT NULL,
    current BOOLEAN NOT NULL DEFAULT false
);

-- =================================================================
--  SECTION 2: CUSTOMER DATA
-- =================================================================
-- This table will be populated by logical replication from the
-- 'east_cost_ecommerce' and 'west_coast_ecommerce' databases. Their 
-- structure must match
-- the publisher's definition exactly. Do NOT insert data manually.
-- =================================================================


-- merged customer data data from the east and west

CREATE TABLE customer.customer (
    id UUID PRIMARY KEY,
    -- PII fields are masked (see replication setup scripts for column-level filtering)
    first_name VARCHAR(50) DEFAULT 'masked',
    last_name VARCHAR(50) DEFAULT 'masked',
    phone_numbers JSONB DEFAULT '{"home": "+1 (555) 123-345", "mobile": "+1 (555) 456-789"}',
    street_address VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(50) NOT NULL,
    origin VARCHAR(4) NOT NULL
);


-- =================================================================
--  SECTION 2: SALES DATA
-- =================================================================
-- Thes tables will be populated by logical replication from the
-- 'east_cost_ecommerce' and 'west_coast_ecommerce' databases. Their 
-- structure must match
-- the publisher's definition exactly. Do NOT insert data manually.
-- =================================================================

CREATE TABLE sales.sales_transaction(
    id UUID PRIMARY KEY,
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id UUID REFERENCES customer (id),
    origin VARCHAR(4)
);

CREATE TABLE sales.sales_transaction_line (
    id UUID PRIMARY KEY,
    sales_transaction_id UUID REFERENCES sales_transaction (id),
    product_variant_id INTEGER NOT NULL REFERENCES product_variant (id),
    qty INTEGER,
    price_at_sale NUMERIC(10, 2)
);

-- =================================================================