-- =================================================================
--  PSQL SCRIPT FOR EAST COST E-COMMERCE DATABASE
-- =================================================================
--  OWNER: Superuser
--  PURPOSE: Creates the database schema for the east coast-specific site.
--           Some tables are populated via logical replication.
-- =================================================================

-- =================================================================
--  SECTION 1: SCHEMA PREPARATION
-- =================================================================

-- Switch connection to created database.
\c east_ecommerce_data
\echo '--> Successfully connected to database: east_ecommerce_data'

\echo '--> Creating the schemata for api, product_refence, inventory, customer, and sales data'

CREATE SCHEMA IF NOT EXISTS api;
CREATE SCHEMA IF NOT EXISTS product_reference; -- replicated from ecommerce_reference_data.product_reference.*
CREATE SCHEMA IF NOT EXISTS inventory; -- private
CREATE SCHEMA IF NOT EXISTS east_customer; -- replicated to analytics.east_customer.*
CREATE SCHEMA IF NOT EXISTS east_sales; -- replicated to analytics.east_sales.*

--- this needs to change. Search paths definitions needs to move into the api calls
\echo '--> Creating the search path at the database level'
ALTER DATABASE east_ecommerce_data SET SEARCH_PATH TO api, product_reference, inventory, east_customer, east_sales; -- permanent change
SET SEARCH_PATH TO api, product_reference, inventory, east_customer, east_sales; -- make sure path is available in current session


-- =================================================================
--  SECTION 2: PRODUCT REFERENCE DATA
-- =================================================================
-- These tables will be populated by logical replication from the
-- 'ecommerce_reference_data' database. Their structure must match
-- the publisher's definition exactly. Do NOT insert data manually.
-- =================================================================

\echo '--> Creating extensions...'
CREATE EXTENSION IF NOT EXISTS btree_gist;


CREATE TABLE product_reference.product_category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product_reference.product_brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product_reference.product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_category_id INTEGER NOT NULL REFERENCES product_reference.product_category (id),
    product_brand_id INTEGER NOT NULL REFERENCES product_reference.product_brand (id),
    label VARCHAR(50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50)
);

CREATE TABLE product_reference.product_variant (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product_reference.product(id) ON DELETE CASCADE,
    attributes JSONB,
    upc VARCHAR(12) NOT NULL
);

CREATE TABLE product_reference.product_variant_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant_id INTEGER NOT NULL REFERENCES product_reference.product_variant (id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    -- DATERANGE where the lower bound is inclusive, and the upper bound is exclusive.
    validity DATERANGE NOT NULL,
    current BOOLEAN NOT NULL DEFAULT false,
    -- Ensures that there are no overlapping price validity periods for the same product and geography.
    EXCLUDE USING GIST (product_variant_id WITH =, validity WITH &&)
);

-- =================================================================
--  SECTION 3: INVENTORY DATA
-- =================================================================
-- These tables exist locally only and represent available inventory levels
-- =================================================================


-- Simplified inventory model
CREATE TABLE inventory.product_variant_inventory (
    product_variant_id INTEGER PRIMARY KEY NOT NULL REFERENCES product_reference.product_variant(id) ON DELETE CASCADE,
    qty INTEGER NOT NULL DEFAULT 0 CHECK (qty >= 0),
    CONSTRAINT uq_inventory_variant UNIQUE (product_variant_id)
);

-- =================================================================
--  SECTION 3: EAST COAST CUSTOMER DATA
-- =================================================================
-- These tables represent EAST Cost customer data
-- They will be replicated to the central analysis server
-- PII can be filtered out by INSERT/UPDATE triggers on the target
-- Using unique schema name to simplify aggregation on the target
-- Using prefix sequences to create readable unique IDs to allow
-- merger of the data on the Central Analytics service while 
-- maintaining the unique primary key
-- =================================================================


-- define prefix sequence to create unique customer ids for the east coast site

CREATE SEQUENCE east_customer.customer_seq;

CREATE TABLE east_customer.customer (
    id TEXT PRIMARY KEY DEFAULT ('east_'|| nextval('east_customer.customer_seq')),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone_numbers JSONB,
    street_address VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(50) NOT NULL
);

-- assign the sequence to the table/column to make sure it gets dropped with the table
ALTER SEQUENCE east_customer.customer_seq OWNED BY east_customer.customer.id;

-- =================================================================
--  SECTION 3: East Coast SALES DATA
-- =================================================================
-- These tables represent the east coast sales data
-- They will be replicated to the central analysis server
-- Using unique schema name to simplify aggregation on the target
-- =================================================================

-- Sales transaction header

CREATE SEQUENCE east_sales.sales_transaction_seq;

CREATE TABLE east_sales.sales_transaction (
    id TEXT PRIMARY KEY DEFAULT ('east_'|| nextval('east_sales.sales_transaction_seq')),
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id TEXT NOT NULL REFERENCES customer(id)
);

ALTER SEQUENCE east_sales.sales_transaction_seq OWNED BY east_sales.sales_transaction.id;


-- Sales transaction line items

CREATE SEQUENCE east_sales.sales_transaction_line_seq;

CREATE TABLE east_sales.sales_transaction_line (
    id TEXT PRIMARY KEY DEFAULT ('east_'|| nextval('east_sales.sales_transaction_line_seq')),
    sales_transaction_id TEXT NOT NULL REFERENCES east_sales.sales_transaction(id) ON DELETE CASCADE,
    product_variant_id INTEGER NOT NULL REFERENCES product_reference.product_variant(id),
    qty INTEGER NOT NULL CHECK (qty > 0),
    price_at_sale NUMERIC(10, 2) NOT NULL CHECK (price_at_sale >= 0)
);

ALTER SEQUENCE east_sales.sales_transaction_line_seq OWNED BY east_sales.sales_transaction_line.id;

/*

Shared East/West API Definitions are in database_definitions/east_ecommerce_data.sql

*/



\echo '*** Script Finished Successfully ***'

