-- =================================================================
--  PSQL SCRIPT FOR E-COMMERCE REFERENCE DATA SETUP
-- =================================================================
--  OWNER: Superuser
--  PURPOSE: Creates the database schema, tables
--           for product reference information.
-- =================================================================

-- =================================================================
--  SECTION 1: SCHEMA PREPARATION
-- =================================================================


-- Switch connection to the database.
\c ecommerce_reference_data

\echo '--> Successfully connected to database: ecommerce_reference_data'

\echo '--> Creating the schemata for api, product_refence, inventory, customer, and sales data'

CREATE SCHEMA IF NOT EXISTS api;
CREATE SCHEMA IF NOT EXISTS product; -- replicated to us/eu_ecommerce_data.product.*
CREATE SCHEMA IF NOT EXISTS internal;

\echo '--> Creating the search path at the database level'

ALTER DATABASE ecommerce_reference_data SET SEARCH_PATH TO api, product, internal; -- permanent change
SET SEARCH_PATH TO api, product, internal; --- make sure path is available in current session

-- =================================================================
--  SECTION 2: EXTENSIONS AND CUSTOM TYPES
-- =================================================================

\echo '--> Creating extensions...'
-- btree_gist is required for using the GIST exclusion constraint on a DATERANGE.
CREATE EXTENSION IF NOT EXISTS btree_gist;


-- =================================================================
--  SECTION 3: TABLE DEFINITIONS
-- =================================================================

\echo '--> Creating product tables...'

CREATE TABLE product.category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product.brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product.country_of_origin (
    brand_id INTEGER PRIMARY KEY REFERENCES brand (id),
    --- three digit ISO 3166-1 A-3
    alpha3_code VARCHAR(3) NOT NULL,
    name TEXT
);

CREATE TABLE product.product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id INTEGER NOT NULL REFERENCES product.category (id),
    brand_id INTEGER NOT NULL REFERENCES product.brand (id),
    label VARCHAR (50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50)
);

CREATE TABLE product.product_variant (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product.product(id) ON DELETE CASCADE,
    attributes JSONB
);

CREATE TABLE product.product_variant_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant_id INTEGER NOT NULL REFERENCES product.product_variant (id) ON DELETE CASCADE,
    -- make sure the prices are always greater 0
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    -- DATERANGE where the lower bound is inclusive, and the upper bound is exclusive.
    validity DATERANGE NOT NULL,
    current BOOLEAN NOT NULL DEFAULT false,
    -- Ensures that there are no overlapping price validity periods for the same product and geography.
    EXCLUDE USING GIST (product_variant_id WITH =, validity WITH &&)
);

ALTER TABLE product.product_variant_price REPLICA IDENTITY FULL;


-- =================================================================
--  SECTION 4: STORED PROCEDURES AND MAINTENANCE QUERIES
-- add/edit/delete/view product categories 
-- add/edit/delete/view product brands
-- add/edit/delete/view products
-- add/edit/delete/view product prices
-- view for products with prices (full and focus)
-- =================================================================

\echo '--> Creating stored procedures and function for data maintenance...'


/*
    API definitions for product.category
    manage_<table_name> can be called with INSERT, UPDATE, and DELETE operations and returns the old and new records as JSONB
    **Read** is implemented through the _<table_name>__vw_ view (or _<table_name>__mv_ for a materialized view)


*/

/*
    Product Category API
    * api.manage_category
    * api.vw_category
*/


CREATE OR REPLACE FUNCTION api.manage_category (
    p_operation_type TEXT,
    p_id INTEGER DEFAULT NULL,
    p_label character varying(50) DEFAULT NULL,
    p_description TEXT DEFAULT NULL
)
RETURNS TABLE (
    operation_type TEXT,
    old_value JSONB,
    new_value JSONB
)
AS $$
DECLARE
    v_old_row JSONB;
    v_new_row JSONB;
    v_inserted_id JSONB;
BEGIN
    IF p_operation_type = 'INSERT' THEN
        INSERT INTO category (label, description)
            VALUES (p_label, p_description)
            RETURNING to_jsonb(NEW) INTO v_new_row;
        RETURN QUERY SELECT 
            'INSERT'::TEXT AS operation_type,
            NULL::JSONB AS old_value, --- there is no old value
            v_new_row AS new_value;

    ELSEIF p_operation_type = 'UPDATE' THEN
        UPDATE category 
            SET
                label = p_label,
                description = p_description
            WHERE id = p_id
            RETURNING to_jsonb (OLD), to_jsonb (NEW) INTO v_old_row, v_new_row;
        -- If no row was updated (p_id not found), return nothing
        IF NOT FOUND THEN
            RETURN;
        END IF;
        -- Return the old and new values as part of a table record
        RETURN QUERY SELECT 
            'UPDATE'::TEXT AS operation_type,
            v_old_row AS old_value,
            v_new_row AS new_value;

    ELSEIF p_operation_type = 'DELETE' THEN
        DELETE FROM category 
            WHERE id = p_id
            RETURNING to_jsonb (OLD) INTO v_old_row;
             -- If no row was deleted (p_id not found), return nothing
            IF NOT FOUND THEN
                RETURN;
            END IF;      
        RETURN QUERY SELECT 
            'DELETE'::TEXT AS operation_type,
            v_old_row AS old_value,
            NULL::JSONB AS new_value;

    ELSE
        RAISE EXCEPTION 'Invalid operation type: %', p_operation_type;
    END IF;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE VIEW api.vw_product_catgory AS
    SELECT id, label, description FROM category;

/*
    Product Brand API
    * api.manage_brand
    * api.vw_brand
*/

CREATE OR REPLACE FUNCTION api.manage_brand (
    p_operation_type TEXT,
    p_id INTEGER DEFAULT NULL,
    p_label character varying(50) DEFAULT NULL,
    p_description TEXT DEFAULT NULL
)
RETURNS TABLE (
    operation_type TEXT,
    old_value JSONB,
    new_value JSONB
)
AS $$
DECLARE
    v_old_row JSONB;
    v_new_row JSONB;
    v_inserted_id JSONB;
BEGIN
    IF p_operation_type = 'INSERT' THEN
        INSERT INTO brand (label, description)
            VALUES (p_label, p_description)
            RETURNING to_jsonb(NEW) INTO v_new_row;
        RETURN QUERY SELECT 
            'INSERT'::TEXT AS operation_type,
            NULL::JSONB AS old_value, --- there is no old value
            v_new_row AS new_value;

    ELSEIF p_operation_type = 'UPDATE' THEN
        UPDATE brand 
            SET
                label = p_label,
                description = p_description
            WHERE id = p_id
            RETURNING to_jsonb (OLD), to_jsonb (NEW) INTO v_old_row, v_new_row;
        -- If no row was updated (p_id not found), return nothing
        IF NOT FOUND THEN
            RETURN;
        END IF;
        -- Return the old and new values as part of a table record
        RETURN QUERY SELECT 
            'UPDATE'::TEXT AS operation_type,
            v_old_row AS old_value,
            v_new_row AS new_value;

    ELSEIF p_operation_type = 'DELETE' THEN
        DELETE FROM brand 
            WHERE id = p_id
            RETURNING to_jsonb (OLD) INTO v_old_row;
             -- If no row was deleted (p_id not found), return nothing
            IF NOT FOUND THEN
                RETURN;
            END IF;      
        RETURN QUERY SELECT 
            'DELETE'::TEXT AS operation_type,
            v_old_row AS old_value,
            NULL::JSONB AS new_value;

    ELSE
        RAISE EXCEPTION 'Invalid operation type: %', p_operation_type;
    END IF;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE VIEW api.vw_brand AS
    SELECT id, label, description FROM brand;

/*
    Product  API
    * api.manage_product
    * api.vw_product
    * api.vw_product_full (category, brand, product, price)
    * api.vw_product_focus (subset of columns from vw_product_full)
*/


CREATE OR REPLACE FUNCTION api.manage_product (
    p_operation_type TEXT,
    p_id INTEGER DEFAULT NULL,
    p_category_id INTEGER DEFAULT NULL,
    p_brand_id INTEGER DEFAULT NULL,
    p_label VARCHAR(50) DEFAULT NULL,
    p_shortdescription VARCHAR(200) DEFAULT NULL,
    p_longdescription TEXT DEFAULT NULL,
    p_image_filename VARCHAR(50) DEFAULT NULL
)
RETURNS TABLE (
    operation_type TEXT,
    old_value JSONB,
    new_value JSONB
)
AS $$
DECLARE
    v_old_row JSONB;
    v_new_row JSONB;
    v_inserted_id JSONB;
BEGIN
    IF p_operation_type = 'INSERT' THEN
        INSERT INTO product (category_id, brand_id, label, shortdescription, longdescription, image_filename)
            VALUES (p_category_id, p_brand_id, p_label, p_shortdescription, p_longdescription, p_image_filename)
            RETURNING to_jsonb(NEW) INTO v_new_row;
        RETURN QUERY SELECT 
            'INSERT'::TEXT AS operation_type,
            NULL::JSONB AS old_value, --- there is no old value
            v_new_row AS new_value;

    ELSEIF p_operation_type = 'UPDATE' THEN
        UPDATE product 
            SET
                category_id = p_category_id,
                brand_id = p_brand_id,
                label = p_label,
                shortdescription = p_shortdescription,
                longdescription = p_longdescription,
                image_filename = p_image_filename
            WHERE id = p_id
            RETURNING to_jsonb (OLD), to_jsonb (NEW) INTO v_old_row, v_new_row;
        -- If no row was updated (p_id not found), return nothing
        IF NOT FOUND THEN
            RETURN;
        END IF;
        -- Return the old and new values as part of a table record
        RETURN QUERY SELECT 
            'UPDATE'::TEXT AS operation_type,
            v_old_row AS old_value,
            v_new_row AS new_value;

    ELSEIF p_operation_type = 'DELETE' THEN
        DELETE FROM product
            WHERE id = p_id
            RETURNING to_jsonb (OLD) INTO v_old_row;
             -- If no row was deleted (p_id not found), return nothing
            IF NOT FOUND THEN
                RETURN;
            END IF;      
        RETURN QUERY SELECT 
            'DELETE'::TEXT AS operation_type,
            v_old_row AS old_value,
            NULL::JSONB AS new_value;

    ELSE
        RAISE EXCEPTION 'Invalid operation type: %', p_operation_type;
    END IF;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE VIEW api.vw_product AS
    SELECT id, category_id, brand_id, label, shortdescription, longdescription, image_filename FROM product;    
   
--- show products with brand, category, and pricing
CREATE OR REPLACE VIEW api.vw_product_full AS  
    SELECT 
        p.id product_id, p.label product_label, p.shortdescription product_shortdescription, p.longdescription product_longdescription, 
        pc.label category_label, pc.description category_description,
        pb.label brand_label, pb.description brand_description,
        pv.attributes product_variant_attributes,
        pvp.price, pvp.validity, pvp.current  
        FROM product p
        JOIN category pc ON p.category_id = pc.id
        JOIN brand pb ON p.brand_id = pb.id
        LEFT JOIN product_variant pv ON p.id = pv.product_id
        LEFT JOIN product_variant_price pvp ON pvp.product_variant_id = pv.id
        ORDER BY p.id, pvp.validity ASC;


--- focused view with a subset of columns
CREATE OR REPLACE VIEW api.vw_product_focus AS 
    SELECT product_id, product_label, product_shortdescription, category_label, brand_label, product_variant_attributes, price, validity, current
        FROM vw_product_full
        WHERE validity @> current_date;

/*
    Product Variant API
    * api.manage_product_variant
    * api.vw_product_variant
*/

CREATE OR REPLACE FUNCTION api.manage_product_variant (
    p_operation_type TEXT,
    p_id INTEGER DEFAULT NULL,
    p_product_id INTEGER DEFAULT NULL,
    p_attributes JSONB DEFAULT NULL
)
RETURNS TABLE (
    operation_type TEXT,
    old_value JSONB,
    new_value JSONB
)
AS $$
DECLARE
    v_old_row JSONB;
    v_new_row JSONB;
    v_inserted_id JSONB;
BEGIN
    IF p_operation_type = 'INSERT' THEN
        INSERT INTO product_variant (product_id, attributes)
            VALUES (p_product_id, p_attributes)
            RETURNING to_jsonb(NEW) INTO v_new_row;
        RETURN QUERY SELECT 
            'INSERT'::TEXT AS operation_type,
            NULL::JSONB AS old_value, --- there is no old value
            v_new_row AS new_value;

    ELSEIF p_operation_type = 'UPDATE' THEN
        UPDATE product_variant 
            SET
                product_id = p_product_id,
                attributes = p_attributes
            WHERE id = p_id
            RETURNING to_jsonb (OLD), to_jsonb (NEW) INTO v_old_row, v_new_row;
        -- If no row was updated (p_id not found), return nothing
        IF NOT FOUND THEN
            RETURN;
        END IF;
        -- Return the old and new values as part of a table record
        RETURN QUERY SELECT 
            'UPDATE'::TEXT AS operation_type,
            v_old_row AS old_value,
            v_new_row AS new_value;

    ELSEIF p_operation_type = 'DELETE' THEN
        DELETE FROM product_variant
            WHERE id = p_id
            RETURNING to_jsonb (OLD) INTO v_old_row;
             -- If no row was deleted (p_id not found), return nothing
            IF NOT FOUND THEN
                RETURN;
            END IF;      
        RETURN QUERY SELECT 
            'DELETE'::TEXT AS operation_type,
            v_old_row AS old_value,
            NULL::JSONB AS new_value;

    ELSE
        RAISE EXCEPTION 'Invalid operation type: %', p_operation_type;
    END IF;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE VIEW api.vw_product_variant AS
    SELECT id, product_id, attributes FROM product_variant;



/*
    Product Price API
    * api.manage_product_price
    * api.vw_product_price
*/

CREATE OR REPLACE FUNCTION api.manage_product_variant_price (
    p_operation_type TEXT,
    p_id INTEGER DEFAULT NULL,
    p_product_variant_id INTEGER DEFAULT NULL,
    p_price NUMERIC DEFAULT NULL,
    p_validity DATERANGE DEFAULT NULL,
    p_current BOOLEAN DEFAULT NULL
)
RETURNS TABLE (
    operation_type TEXT,
    old_value JSONB,
    new_value JSONB
)
AS $$
DECLARE
    v_old_row JSONB;
    v_new_row JSONB;
    v_inserted_id JSONB;
BEGIN
    IF p_operation_type = 'INSERT' THEN
        INSERT INTO product_variant_price (product_variant_id, price, validity, current)
            VALUES (p_product_variant_id, p_price, p_validity, p_current)
            RETURNING to_jsonb(NEW) INTO v_new_row;
        RETURN QUERY SELECT 
            'INSERT'::TEXT AS operation_type,
            NULL::JSONB AS old_value, --- there is no old value
            v_new_row AS new_value;

    ELSEIF p_operation_type = 'UPDATE' THEN
        UPDATE product_variant_price 
            SET
                product_variant_id = p_product_variant_id,
                price = p_price,
                validity = p_validity,
                current = p_current
            WHERE id = p_id
            RETURNING to_jsonb (OLD), to_jsonb (NEW) INTO v_old_row, v_new_row;
        -- If no row was updated (p_id not found), return nothing
        IF NOT FOUND THEN
            RETURN;
        END IF;
        -- Return the old and new values as part of a table record
        RETURN QUERY SELECT 
            'UPDATE'::TEXT AS operation_type,
            v_old_row AS old_value,
            v_new_row AS new_value;

    ELSEIF p_operation_type = 'DELETE' THEN
        DELETE FROM product_variant_price
            WHERE id = p_id
            RETURNING to_jsonb (OLD) INTO v_old_row;
             -- If no row was deleted (p_id not found), return nothing
            IF NOT FOUND THEN
                RETURN;
            END IF;      
        RETURN QUERY SELECT 
            'DELETE'::TEXT AS operation_type,
            v_old_row AS old_value,
            NULL::JSONB AS new_value;

    ELSE
        RAISE EXCEPTION 'Invalid operation type: %', p_operation_type;
    END IF;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE VIEW api.vw_product_variant_price AS
    SELECT id, product_variant_id, price, validity, current FROM product_variant_price;

/*
    Miscellaneous API elements


*/
CREATE OR REPLACE PROCEDURE api.update_current_price_flags()
    LANGUAGE SQL
    AS $$
    UPDATE product.product_variant_price
    SET current = (validity @> current_date);
    $$;

--- identify any product variants without current prices
CREATE OR REPLACE VIEW api.vw_product_variant_without_current_price AS 
    SELECT 
        pv.id AS product_variant_id, pv.attributes AS product_variant_attributes, 
        p.id as product_id, p.label AS product_label 
    FROM product_variant pv 
    JOIN product p ON p.id = pv.product_id
    WHERE NOT EXISTS 
        (SELECT 1 FROM product_variant_price pvp 
            WHERE pvp.current = TRUE 
                AND pvp.product_variant_id = pv.id);


--- views






\echo '*** Script Finished Successfully ***'
