-- =================================================================
--  PSQL SCRIPT FOR E-COMMERCE REFERENCE DATA SETUP
-- =================================================================
--  OWNER: Superuser
--  PURPOSE: Creates the database schema, tables
--           for product reference information.
-- =================================================================

-- =================================================================
--  SECTION 1: SYSTEM AND DATABASE PREPARATION
-- =================================================================
-- Note: These initial commands should be run by a superuser connected
-- to a maintenance database (like 'postgres').

\echo '[SYSTEM PREP] ==> Setting WAL_LEVEL to logical for replication...'
-- This requires a server restart to take effect. It only needs to be
-- run once per PostgreSQL instance.
ALTER SYSTEM SET wal_level = logical;
\echo 'NOTE: A server restart is required for WAL_LEVEL change to apply.'


\echo '[DATABASE PREP] ==> Preparing to drop and recreate the database.'
-- Terminate all active connections to the target database before dropping it.
-- This is a more controlled approach than using WITH (FORCE).
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = 'ecommerce_reference_data' AND pid <> pg_backend_pid();

DROP DATABASE IF EXISTS ecommerce_reference_data;

\echo '[DATABASE PREP] ==> Creating the database...'
CREATE DATABASE ecommerce_reference_data;

-- Switch connection to the newly created database.
\c ecommerce_reference_data

\echo '--> Successfully connected to database: ecommerce_reference_data'

\echo '--> Creating the schemata for api, product_refence, inventory, customer, and sales data'

CREATE SCHEMA IF NOT EXISTS api;
CREATE SCHEMA IF NOT EXISTS product_reference; -- replicated to us/eu_ecommerce_data.product_reference.*
CREATE SCHEMA IF NOT EXISTS internal;

\echo '--> Creating the search path at the database level'

ALTER DATABASE ecommerce_reference_data SET SEARCH_PATH TO api, product_reference, internal; -- permanent change
SET SEARCH_PATH TO api, product_reference, internal; --- make sure path is available in current session

-- =================================================================
--  SECTION 2: EXTENSIONS AND CUSTOM TYPES
-- =================================================================

\echo '--> Creating extensions...'
-- btree_gist is required for using the GIST exclusion constraint on a DATERANGE.
CREATE EXTENSION IF NOT EXISTS btree_gist;

\echo '--> Creating custom ENUM types...'
-- Using ENUMs helps ensure data integrity for controlled vocabularies.
CREATE TYPE internal.sales_geo AS ENUM ('EU', 'US');
CREATE TYPE internal.sales_currency AS ENUM ('USD', 'EURO');


-- =================================================================
--  SECTION 3: TABLE DEFINITIONS
-- =================================================================

\echo '--> Creating product_reference tables...'

CREATE SCHEMA IF NOT EXISTS product_reference;

CREATE TABLE product_reference.product_category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product_reference.product_brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product_reference.product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_category_id INTEGER NOT NULL REFERENCES product_reference.product_category (id),
    product_brand_id INTEGER NOT NULL REFERENCES product_reference.product_brand (id),
    label VARCHAR (50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50)
);

CREATE TABLE product_reference.product_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product_reference.product (id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    currency VARCHAR(4) NOT NULL,
    geography VARCHAR(4) NOT NULL,
    -- DATERANGE where the lower bound is inclusive, and the upper bound is exclusive.
    validity DATERANGE NOT NULL,
    current BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT check_currency_geo_consistency CHECK (
        (geography = 'US' AND currency = 'USD') OR
        (geography = 'EU' AND currency = 'EURO')
    ),
    -- Ensures that there are no overlapping price validity periods for the same product variant and geography.
    EXCLUDE USING GIST (product_id WITH =, geography WITH =, validity WITH &&)
);

-- Set REPLICA IDENTITY to FULL for the table that has row-filtered replication.
-- This ensures that old row data is available for logical replication updates.
ALTER TABLE product_reference.product_price REPLICA IDENTITY FULL;


-- =================================================================
--  SECTION 4: STORED PROCEDURES AND MAINTENANCE QUERIES
-- add/edit/delete product categories
-- add/edit/delete product brands
-- add/edit/delete products
-- add/edit/delete product prices
-- view for products with prices
-- =================================================================

\echo '--> Creating stored procedures and function for data maintenance...'


/*
    API definitions for product_reference.product_category
    create_<table_name> will return the new record if the update is successful, _NULL_ otherwise. 
    update_<table_name> will return the new record, and the old record if the update is successful, NULL otherwise. 
    delete__<table_name> will return the deleted record, _NULL_ otherwise.
    **Read** is implemented through the _<table_name>__vw_ view (or _<table_name>__mv_ for a materialized view)


*/

/*
    Product Category API
    * api.add_product_category
    * api.update_product_category
    * api.delete_product_category
    * api.vw_product_category
*/

CREATE OR REPLACE FUNCTION 
        api.add_product_category(
        p_label VARCHAR(50), 
        p_description TEXT) 
        RETURNS product_category
    AS
      $$
        INSERT INTO product_category (label, description) 
            VALUES (p_label, p_description) 
            RETURNING *;
    $$ LANGUAGE SQL;    


CREATE OR REPLACE FUNCTION api.update_product_category(
        IN p_id INTEGER, 
        IN p_label VARCHAR(50), 
        IN p_description TEXT,
        OUT old_id INTEGER,
        OUT old_label TEXT,
        OUT old_description TEXT,
        OUT new_id INTEGER,
        OUT new_label TEXT,
        OUT new_description TEXT)
    AS 
    $$
        DECLARE
        BEGIN 
        UPDATE product_category 
            SET label = p_label, description = p_description
            WHERE id = p_id
            RETURNING 
                old.id, old.label, old.description, new.id, new.label,new.description 
                INTO 
                old_id,old_label, old_description, new_id, new_label, new_description;
        END    
    $$ LANGUAGE PLPGSQL; 
    
CREATE OR REPLACE FUNCTION api.delete_product_category(
        p_id INTEGER) 
    RETURNS product_category
    AS 
    $$
    DECLARE
        v_record product_category := NULL;
    BEGIN    
            DELETE FROM product_category WHERE id = p_id RETURNING * INTO v_record;
            RETURN v_record;
    EXCEPTION
    --- 23503 & 2300
        WHEN integrity_constraint_violation or check_violation THEN 
            RAISE NOTICE 'Foreign Key Violation. Delete of product category % failed', p_id;
            RETURN v_record;
        WHEN others THEN
            RAISE NOTICE 'Delete of product category % failed', p_id;
            RETURN v_record;
    
    END        
    $$ LANGUAGE PLPGSQL;   

CREATE OR REPLACE VIEW api.vw_product_catgory AS
    SELECT id, label, description FROM product_category;

/*
    Product Brand API
    * api.add_product_brand
    * api.update_product_brand
    * api.delete_product_brand
    * api.vw_product_brand
*/

CREATE OR REPLACE VIEW api.vw_product_brand AS
    SELECT id, label, description FROM product_brand;



/*
    Miscellaneous API elements


*/
CREATE OR REPLACE PROCEDURE api.update_current_price_flags()
    LANGUAGE SQL
    AS $$
    UPDATE product_reference.product_price
    SET current = (validity @> current_date);
    $$;

--- identify any products without current prices
CREATE OR REPLACE VIEW api.vw_product_without_current_price AS 
    SELECT p.id, p.label FROM product p 
        WHERE NOT EXISTS 
        (SELECT 1 FROM product_price pp 
            WHERE pp.current = TRUE 
                AND pp.product_id = p.id);


--- views



CREATE OR REPLACE VIEW api.vw_product AS
    SELECT id, product_category_id, product_brand_id, label, shortdescription, longdescription, image_filename FROM product_brand;    

CREATE OR REPLACE VIEW api.vw_product_price AS
    SELECT id, product_id, price, currency, geography, validity, current FROM product_price;      




--- show products with brand, category, and pricing
CREATE OR REPLACE VIEW api.vw_product_full AS  
    SELECT 
        p.id product_id, p.label product_label, p.shortdescription product_shortdescription, p.longdescription product_longdescription, 
        pc.label product_category_label, pc.description product_category_description,
        pb.label product_brand_label, pb.description product_brand_description,
        pp.price, pp.currency, pp.geography, pp.validity, pp.current  
        FROM product p
        JOIN product_category pc ON p.product_category_id = pc.id
        JOIN product_brand pb ON p.product_brand_id = pb.id
        JOIN product_price pp ON pp.product_id = p.id
        ORDER BY p.id, pp.geography, pp.validity ASC;


--- focused view with a subset of columns
CREATE OR REPLACE VIEW api.vw_product_focus AS 
    SELECT product_id, product_label, product_shortdescription, product_category_label, product_brand_label, price, currency, validity, current
        FROM vw_product_full
        WHERE validity @> current_date;


\echo '*** Script Finished Successfully ***'
