-- =================================================================
--  PSQL SCRIPT FOR EU E-COMMERCE SUBSCRIBER DATABASE
-- =================================================================
--  OWNER: Superuser
--  PURPOSE: Creates the database schema for the EU-specific site.
--           Some tables are populated via logical replication.
-- =================================================================

-- =================================================================
--  SECTION 1: DATABASE PREPARATION
-- =================================================================
-- Note: Run this script while connected to a neutral DB (e.g., 'postgres').

\echo '[DATABASE PREP] ==> Preparing to drop and recreate the database.'

-- Terminate active connections before dropping the database for a safe teardown.
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE datname = 'eu_ecommerce_data' AND pid <> pg_backend_pid();

DROP DATABASE IF EXISTS eu_ecommerce_data;

\echo '[DATABASE PREP] ==> Creating the database...'
CREATE DATABASE eu_ecommerce_data;

-- Switch connection to the newly created database.
\c eu_ecommerce_data
\echo '--> Successfully connected to database: eu_ecommerce_data'

\echo '--> Creating the schemata for api, product_refence, inventory, customer, and sales data'

CREATE SCHEMA IF NOT EXISTS api;
CREATE SCHEMA IF NOT EXISTS product_reference; -- replicated from ecommerce_reference_data.product_reference.*
CREATE SCHEMA IF NOT EXISTS inventory; -- private
CREATE SCHEMA IF NOT EXISTS eu_customer; -- replicated to analytics.eu_customer.*
CREATE SCHEMA IF NOT EXISTS eu_sales; -- replicated to analytics.eu_sales.*

--- this needs to change. Search paths definitions needs to move into the api calls
\echo '--> Creating the search path at the database level'
ALTER DATABASE eu_ecommerce_data SET SEARCH_PATH TO api, product_reference, inventory, eu_customer, eu_sales; -- permanent change
SET SEARCH_PATH TO api, product_reference, inventory, eu_customer, eu_sales; -- make sure path is available in current session


-- =================================================================
--  SECTION 2: PRODUCT REFERENCE DATA
-- =================================================================
-- These tables will be populated by logical replication from the
-- 'ecommerce_reference_data' database. Their structure must match
-- the publisher's definition exactly. Do NOT insert data manually.
-- =================================================================

\echo '--> Creating extensions...'
CREATE EXTENSION IF NOT EXISTS btree_gist;


CREATE TABLE product_reference.product_category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product_reference.product_brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product_reference.product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_category_id INTEGER NOT NULL REFERENCES product_reference.product_category (id),
    product_brand_id INTEGER NOT NULL REFERENCES product_reference.product_brand (id),
    label VARCHAR(50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50)
);

CREATE TABLE product_reference.product_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product_reference.product (id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    currency VARCHAR(4) NOT NULL,
    geography VARCHAR(4) NOT NULL,
    -- DATERANGE where the lower bound is inclusive, and the upper bound is exclusive.
    validity DATERANGE NOT NULL,
    current BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT check_currency_geo_consistency CHECK (
        (geography = 'US' AND currency = 'USD') OR
        (geography = 'EU' AND currency = 'EURO')
    ),
    -- Ensures that there are no overlapping price validity periods for the same product variant and geography.
    EXCLUDE USING GIST (product_id WITH =, geography WITH =, validity WITH &&)
);

-- =================================================================
--  SECTION 3: INVENTORY DATA
-- =================================================================
-- These tables exist locally only and represent available inventory levels
-- =================================================================


-- Simplified inventory model
CREATE TABLE inventory.product_inventory (
    product_id INTEGER PRIMARY KEY NOT NULL REFERENCES product_reference.product(id) ON DELETE CASCADE,
    qty INTEGER NOT NULL DEFAULT 0 CHECK (qty >= 0),
    CONSTRAINT uq_inventory_variant UNIQUE (product_id)
);

-- =================================================================
--  SECTION 3: EU CUSTOMER DATA
-- =================================================================
-- These tables represent EU customer data
-- They will be replicated to the central analysis server
-- PII can be filtered out by INSERT/UPDATE triggers on the target
-- Using unique schema name to simplify aggregation on the target
-- =================================================================

-- Simplified customer model
CREATE TABLE eu_customer.customer (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone_numbers JSONB,
    street_address VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(50) NOT NULL
);

-- =================================================================
--  SECTION 3: US SALES DATA
-- =================================================================
-- These tables represent US sales data
-- They will be replicated to the central analysis server
-- Using unique schema name to simplify aggregation on the target
-- =================================================================


-- Sales transaction header
CREATE TABLE eu_sales.sales_transaction (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id INTEGER NOT NULL REFERENCES customer(id)
);

-- Sales transaction line items
CREATE TABLE eu_sales.sales_transaction_line (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sales_transaction_id UUID NOT NULL REFERENCES eu_sales.sales_transaction(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES product_reference.product(id),
    qty INTEGER NOT NULL CHECK (qty > 0),
    price_at_sale NUMERIC(10, 2) NOT NULL CHECK (price_at_sale >= 0)
);

\echo '*** Script Finished Successfully ***'

