-- =================================================================
--  PSQL SCRIPT FOR WEST COAST E-COMMERCE DATABASE
-- =================================================================
--  OWNER: Superuser
--  PURPOSE: Creates the database schema for the west coast-specific site.
--           Some tables are populated via logical replication.
-- =================================================================

-- =================================================================
--  SECTION 1: SCHEMA PREPARATION
-- =================================================================

-- Switch connection to the database.


\c west_ecommerce_data
\echo '--> Successfully connected to database: west_ecommerce_data'

\echo '--> Creating the schemata for api, product_refence, inventory, customer, and sales data'

CREATE SCHEMA IF NOT EXISTS api;
CREATE SCHEMA IF NOT EXISTS product; -- replicated from ecommerce_reference_data.product.*
CREATE SCHEMA IF NOT EXISTS inventory; -- private
CREATE SCHEMA IF NOT EXISTS west_customer; -- replicated to analytics.west_customer.*
CREATE SCHEMA IF NOT EXISTS west_sales; -- replicated to analytics.west_sales.*

\echo '--> Creating the search path at the database level'
ALTER DATABASE west_ecommerce_data SET SEARCH_PATH TO api, product, inventory, west_customer, west_sales; -- permanent change
SET SEARCH_PATH TO api, product, inventory, west_customer, west_sales; -- make sure path is available in current session


-- =================================================================
--  SECTION 2: PRODUCT REFERENCE DATA
-- =================================================================
-- These tables will be populated by logical replication from the
-- 'ecommerce_reference_data' database. Their structure must match
-- the publisher's definition exactly. Do NOT insert data manually.
-- =================================================================

\echo '--> Creating extensions...'
CREATE EXTENSION IF NOT EXISTS btree_gist;


CREATE TABLE product.category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product.brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product.product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id INTEGER NOT NULL REFERENCES product.category (id),
    brand_id INTEGER NOT NULL REFERENCES product.brand (id),
    label VARCHAR(50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50)
);

CREATE TABLE product.product_variant (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product.product(id) ON DELETE CASCADE,
    attributes JSONB
);

CREATE TABLE product.product_variant_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant_id INTEGER NOT NULL REFERENCES product.product_variant (id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    -- DATERANGE where the lower bound is inclusive, and the upper bound is exclusive.
    validity DATERANGE NOT NULL,
    current BOOLEAN NOT NULL DEFAULT false,
    -- Ensures that there are no overlapping price validity periods for the same product and geography.
    EXCLUDE USING GIST (product_variant_id WITH =, validity WITH &&)
);

-- =================================================================
--  SECTION 3: INVENTORY DATA
-- =================================================================
-- These tables exist locally only and represent available inventory levels
-- =================================================================


-- Simplified inventory model
CREATE TABLE inventory.product_variant_inventory (
    product_variant_id INTEGER PRIMARY KEY NOT NULL REFERENCES product.product_variant(id) ON DELETE CASCADE,
    qty INTEGER NOT NULL DEFAULT 0 CHECK (qty >= 0),
    CONSTRAINT uq_inventory_variant UNIQUE (product_variant_id)
);

-- =================================================================
--  SECTION 3: WEST COAST CUSTOMER DATA
-- =================================================================
-- These tables represent West Coast customer data
-- They will be replicated to the central analysis server
-- PII can be filtered out by INSERT/UPDATE triggers on the target
-- Using unique schema name to simplify aggregation on the target
-- Using prefix sequences to create readable unique IDs to allow
-- merger of the data on the Central Analytics service while 
-- maintaining the unique primary key
-- =================================================================

-- define prefix sequence to create unique customer ids for the east coast site

CREATE SEQUENCE west_customer.customer_seq;

CREATE TABLE west_customer.customer (
    id TEXT PRIMARY KEY DEFAULT ('west_'|| nextval('west_customer.customer_seq')),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone_numbers JSONB,
    street_address VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(50) NOT NULL
);

-- assign the sequence to the table/column to make sure it gets dropped with the table
ALTER SEQUENCE west_customer.customer_seq OWNED BY west_customer.customer.id;

-- =================================================================
--  SECTION 3: WEST COAST SALES DATA
-- =================================================================
-- These tables represent West Coast sales data
-- They will be replicated to the central analysis server
-- Using unique schema name to simplify aggregation on the target
-- =================================================================

CREATE SEQUENCE west_sales.sales_transaction_seq;

CREATE TABLE west_sales.sales_transaction (
    id TEXT PRIMARY KEY DEFAULT ('west_'|| nextval('west_sales.sales_transaction_seq')),
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id TEXT NOT NULL REFERENCES customer(id)
);

ALTER SEQUENCE west_sales.sales_transaction_seq OWNED BY west_sales.sales_transaction.id;


-- Sales transaction line items

CREATE SEQUENCE west_sales.sales_transaction_line_seq;

CREATE TABLE west_sales.sales_transaction_line (
    id TEXT PRIMARY KEY DEFAULT ('west_'|| nextval('west_sales.sales_transaction_line_seq')),
    sales_transaction_id TEXT NOT NULL REFERENCES west_sales.sales_transaction(id) ON DELETE CASCADE,
    product_variant_id INTEGER NOT NULL REFERENCES product.product_variant(id),
    qty INTEGER NOT NULL CHECK (qty > 0),
    price_at_sale NUMERIC(10, 2) NOT NULL CHECK (price_at_sale >= 0)
);

ALTER SEQUENCE west_sales.sales_transaction_line_seq OWNED BY west_sales.sales_transaction_line.id;

/*

Shared East/West API Definitions are in database_definitions/east_ecommerce_data.sql

*/

\echo '*** Script Finished Successfully ***'

