-- =================================================================
--  PSQL SCRIPT FOR WEST COAST E-COMMERCE DATABASE
-- =================================================================
--  OWNER: Superuser
--  PURPOSE: Creates the database schema for the west coast-specific site.
--           Some tables are populated via logical replication.
-- =================================================================

-- =================================================================
--  SECTION 1: SCHEMA PREPARATION
-- =================================================================

-- Switch connection to the database.


\c west_ecommerce_data
\echo '--> Successfully connected to database: west_ecommerce_data'

\echo '--> Creating the schemata for api, product_refence, inventory, customer, and sales data'

CREATE SCHEMA IF NOT EXISTS api;
CREATE SCHEMA IF NOT EXISTS product; -- replicated from ecommerce_reference_data.product.*
CREATE SCHEMA IF NOT EXISTS inventory; -- private
CREATE SCHEMA IF NOT EXISTS customer; -- replicated to analytics.customer.*
CREATE SCHEMA IF NOT EXISTS sales; -- replicated to analytics.sales.*

\echo '--> Creating the search path at the database level'
ALTER DATABASE west_ecommerce_data SET SEARCH_PATH TO api, product, inventory, customer, sales; -- permanent change
SET SEARCH_PATH TO api, product, inventory, customer, sales; -- make sure path is available in current session


-- =================================================================
--  SECTION 2: PRODUCT REFERENCE DATA
-- =================================================================
-- These tables will be populated by logical replication from the
-- 'ecommerce_reference_data' database. Their structure must match
-- the publisher's definition exactly. Do NOT insert data manually.
-- =================================================================

\echo '--> Creating extensions...'
CREATE EXTENSION IF NOT EXISTS btree_gist;


CREATE TABLE product.category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product.brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product.country_of_origin (
    brand_id INTEGER PRIMARY KEY REFERENCES brand (id),
    --- three digit ISO 3166-1 A-3
    alpha3_code VARCHAR(3) NOT NULL,
    name TEXT
);

CREATE TABLE product.product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id INTEGER NOT NULL REFERENCES product.category (id),
    brand_id INTEGER NOT NULL REFERENCES product.brand (id),
    label VARCHAR(50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50)
);

CREATE TABLE product.product_variant (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product.product(id) ON DELETE CASCADE,
    attributes JSONB
);

CREATE TABLE product.product_variant_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant_id INTEGER NOT NULL REFERENCES product.product_variant (id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    -- DATERANGE where the lower bound is inclusive, and the upper bound is exclusive.
    validity DATERANGE NOT NULL,
    current BOOLEAN NOT NULL DEFAULT false,
    -- Ensures that there are no overlapping price validity periods for the same product and geography.
    EXCLUDE USING GIST (product_variant_id WITH =, validity WITH &&)
);

-- =================================================================
--  SECTION 3: INVENTORY DATA
-- =================================================================
-- These tables exist locally only and represent available inventory levels
-- =================================================================


-- Simplified inventory model
CREATE TABLE inventory.product_variant_inventory (
    product_variant_id INTEGER PRIMARY KEY NOT NULL REFERENCES product.product_variant(id) ON DELETE CASCADE,
    qty INTEGER NOT NULL DEFAULT 0 CHECK (qty >= 0),
    CONSTRAINT uq_inventory_variant UNIQUE (product_variant_id)
);

-- =================================================================
--  SECTION 3: WEST COAST CUSTOMER DATA
-- =================================================================
-- These tables represent West Coast customer data
-- They will be replicated to the central analysis server
-- PII will be filtered out by INSERT/UPDATE triggers on the target
-- =================================================================


CREATE TABLE customer.customer (
    id UUID PRIMARY KEY DEFAULT uuidv7(),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    phone_numbers JSONB,
    street_address VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(50) NOT NULL,
    origin VARCHAR(4) NOT NULL DEFAULT :'origin' -- variable set in master_setup.sql
);

CREATE INDEX idx_customer_lastname_firstname ON customer.customer(last_name, first_name);
-- =================================================================
--  SECTION 3: WEST COAST SALES DATA
-- =================================================================
-- These tables represent West Coast sales data
-- They will be replicated to the central analysis server
-- =================================================================

CREATE TABLE sales.sales_transaction (
    id UUID PRIMARY KEY DEFAULT uuidV7(),
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id UUID NOT NULL REFERENCES customer(id),
    origin VARCHAR(4) NOT NULL DEFAULT :'origin' -- variable set in master_setup.sql
);

-- Sales transaction line items

CREATE TABLE sales.sales_transaction_line (
    id UUID PRIMARY KEY DEFAULT uuidV7(),
    sales_transaction_id UUID NOT NULL REFERENCES sales_transaction(id) ON DELETE CASCADE,
    product_variant_id INTEGER NOT NULL REFERENCES product.product_variant(id),
    qty INTEGER NOT NULL CHECK (qty > 0),
    price_at_sale NUMERIC(10, 2) NOT NULL CHECK (price_at_sale >= 0)
);

/*

Shared East/West API Definitions are in database_definitions/east_ecommerce_data.sql

*/

\echo '*** Script Finished Successfully ***'

