INSERT INTO product.product (id, category_id, brand_id, label, shortdescription, longdescription, image_filename)
    VALUES
      --- dress shirt Gap
      (1,2,1, 'Dress shirt by The Gap','Classic mens dress shirt from The Gap —tailored fit, premium cotton, versatile for work or formal wear.',
      'Premium Mens Dress Shirt Timeless Style and Unmatched Comfort. Upgrade your wardrobe with this classic mens dress shirt, designed for sophistication and ease. Made from high quality 100 percent cotton or breathable cotton blend fabric, this shirt offers all day comfort while keeping a sharp, professional look. The tailored fit enhances your silhouette, making it perfect for pairing with suits or wearing solo for business casual style. Key features include a button down or spread collar for flexible styling, single button cuffs for a polished finish, and a sturdy button placket built to last. Available in solid colors, subtle stripes, or minimalist patterns, this shirt suits any occasion from office meetings to formal events. Built for convenience, this shirt is wrinkle resistant for easy care and machine washable for quick maintenance. The reinforced stitching and durable seams ensure long lasting wear, while the breathable fabric keeps you cool and comfortable all day. Sizes range from S to XXL, making this dress shirt a versatile essential for every modern mans wardrobe. Whether dressing for work or a special event, this shirt delivers refined style, exceptional comfort, and reliable quality.',
      'dress_shirt.jpg'),
      --- dress shirt Boss
      (2,2,2, 'Dress shirt by Boss', 'Classic mens dress shirt—tailored fit by Boss, premium cotton, versatile for work or formal wear.',
      'Premium Mens Dress Shirt Timeless Style and Unmatched Comfort. Upgrade your wardrobe with this classic mens dress shirt, designed for sophistication and ease. Made from high quality 100 percent cotton or breathable cotton blend fabric, this shirt offers all day comfort while keeping a sharp, professional look. The tailored fit enhances your silhouette, making it perfect for pairing with suits or wearing solo for business casual style. Key features include a button down or spread collar for flexible styling, single button cuffs for a polished finish, and a sturdy button placket built to last. Available in solid colors, subtle stripes, or minimalist patterns, this shirt suits any occasion from office meetings to formal events. Built for convenience, this shirt is wrinkle resistant for easy care and machine washable for quick maintenance. The reinforced stitching and durable seams ensure long lasting wear, while the breathable fabric keeps you cool and comfortable all day. Sizes range from S to XXL, making this dress shirt a versatile essential for every modern mans wardrobe. Whether dressing for work or a special event, this shirt delivers refined style, exceptional comfort, and reliable quality.',
      'dress_shirt.jpg'),
      --- dress shirt Eaton
      (3,2, 17, 'Dress shirt by Eaton', 'Classic mens dress shirt—tailored fit by Eaton, premium cotton, versatile for work or formal wear.',
      'Premium Mens Dress Shirt Timeless Style and Unmatched Comfort. Upgrade your wardrobe with this classic mens dress shirt, designed for sophistication and ease. Made from high quality 100 percent cotton or breathable cotton blend fabric, this shirt offers all day comfort while keeping a sharp, professional look. The tailored fit enhances your silhouette, making it perfect for pairing with suits or wearing solo for business casual style. Key features include a button down or spread collar for flexible styling, single button cuffs for a polished finish, and a sturdy button placket built to last. Available in solid colors, subtle stripes, or minimalist patterns, this shirt suits any occasion from office meetings to formal events. Built for convenience, this shirt is wrinkle resistant for easy care and machine washable for quick maintenance. The reinforced stitching and durable seams ensure long lasting wear, while the breathable fabric keeps you cool and comfortable all day. Sizes range from S to XXL, making this dress shirt a versatile essential for every modern mans wardrobe. Whether dressing for work or a special event, this shirt delivers refined style, exceptional comfort, and reliable quality.',
      'dress_shirt.jpg'),
      --- Oxford shirt Gap
      (4,2,1, 'Mens Classic Oxford Shirt by The Gap', 'Timeless mens Oxford shirt in 100% cotton from The Gap.', 
      'The Oxford button-down shirt is a cornerstone of classic American style, revered for its effortless versatility, timeless design, and understated elegance. Originating in the early 20th century,  it was popularized by Brooks Brothers, who adapted the button-down collar from English polo players to prevent flapping during matches. Made from Oxford cloth—a durable, slightly textured basketweave cotton—this shirt strikes the perfect balance between casual and refined, making it a go-to for both professional and leisure wear. The defining feature is its soft-rolling button-down collar, which adds a touch of relaxed sophistication, distinguishing it from dressier formal shirts. Available in a range of essential colors (crisp white, light blue, pale pink) and subtle patterns (university stripes, tattersall checks, or classic solids), it effortlessly pairs with chinos, jeans, blazers, or suits. The slightly thicker Oxford fabric ensures durability while remaining breathable and comfortable for all-day wear. Designed with a traditional fit (though slim and modern cuts are also available), it features a button-through front, single chest pocket (optional), and reinforced stitching for longevity. Whether dressed up with a tie and wool trousers or worn casually with rolled sleeves and shorts, the Oxford button-down transitions seamlessly from office to weekend. A favorite among preppy, Ivy League, and business-casual wardrobes, it remains a wardrobe essential—a symbol of enduring style that never goes out of fashion.',
      'oxford_shirt.jpg'),
      --- Oxford shirt Boss
      (5,2,2, 'Mens Classic Oxford Shirt from Boss', 'Timeless mens Oxford shirt in 100% cotton.', 
      'The Oxford button-down shirt is a cornerstone of classic American style, revered for its effortless versatility, timeless design, and understated elegance. Originating in the early 20th century,  it was popularized by Brooks Brothers, who adapted the button-down collar from English polo players to prevent flapping during matches. Made from Oxford cloth—a durable, slightly textured basketweave cotton—this shirt strikes the perfect balance between casual and refined, making it a go-to for both professional and leisure wear. The defining feature is its soft-rolling button-down collar, which adds a touch of relaxed sophistication, distinguishing it from dressier formal shirts. Available in a range of essential colors (crisp white, light blue, pale pink) and subtle patterns (university stripes, tattersall checks, or classic solids), it effortlessly pairs with chinos, jeans, blazers, or suits. The slightly thicker Oxford fabric ensures durability while remaining breathable and comfortable for all-day wear. Designed with a traditional fit (though slim and modern cuts are also available), it features a button-through front, single chest pocket (optional), and reinforced stitching for longevity. Whether dressed up with a tie and wool trousers or worn casually with rolled sleeves and shorts, the Oxford button-down transitions seamlessly from office to weekend. A favorite among preppy, Ivy League, and business-casual wardrobes, it remains a wardrobe essential—a symbol of enduring style that never goes out of fashion.',
      'oxford_shirt.jpg'),
      --- Gap T-shirt
      (6, 2, 1, 'T-Shirt by The Gap', 'Short sleeved fitted T-shirt from Gap',
      'Mens T-Shirt: Bold, Edgy, and Unapologetically Cool. The Mens T-Shirt embodies rebellious spirit and Italian craftsmanship, blending streetwear attitude with premium quality. Designed for the confident, fashion-forward man, it features soft, heavyweight cotton for a structured yet comfortable fit, ensuring durability and effortless style. The signature distressed detailing, bold graphics, or minimalist logo prints make a statement, whether youre rocking it with ripped jeans, tailored joggers, or a leather jacket. Cut for a slim or relaxed fit (depending on the style), it offers a modern silhouette that flatters without restricting movement. The reinforced stitching, double-stitched hems, and high-quality screen-printing ensure long-lasting wear, even after repeated washes. From classic crewnecks to edgy oversized cuts, Diesel’s T-shirts cater to diverse tastes—whether you prefer understated monochrome styles or eye-catching, avant-garde designs. Perfect for layering under a blazer for a high-low look or wearing solo for casual streetwear vibes, this T-shirt is a versatile staple in any contemporary wardrobe. With its unmistakable  edge, its more than just a basic—its a bold expression of individuality.',
      't-shirt.jpg'),
      --- Diesel T-Shirt        
      (7, 2, 3, 'T-Shirt by Diesel', 'Short sleeved fitted T-shirt by Diesel',
      'Mens T-Shirt: Bold, Edgy, and Unapologetically Cool. The Mens T-Shirt embodies rebellious spirit and Italian craftsmanship, blending streetwear attitude with premium quality. Designed for the confident, fashion-forward man, it features soft, heavyweight cotton for a structured yet comfortable fit, ensuring durability and effortless style. The signature distressed detailing, bold graphics, or minimalist logo prints make a statement, whether youre rocking it with ripped jeans, tailored joggers, or a leather jacket. Cut for a slim or relaxed fit (depending on the style), it offers a modern silhouette that flatters without restricting movement. The reinforced stitching, double-stitched hems, and high-quality screen-printing ensure long-lasting wear, even after repeated washes. From classic crewnecks to edgy oversized cuts, Diesel’s T-shirts cater to diverse tastes—whether you prefer understated monochrome styles or eye-catching, avant-garde designs. Perfect for layering under a blazer for a high-low look or wearing solo for casual streetwear vibes, this T-shirt is a versatile staple in any contemporary wardrobe. With its unmistakable  edge, its more than just a basic—its a bold expression of individuality.',
      'diesel_t-shirt.jpg'),
      --- Levis Jeans
      (8, 1, 3, '501 Original Fit Jeans', 'The original blue jean since 1873 from Levis.',
      'Levis® 501® Original Fit Jeans. The Icon That Started It All. Born in 1873 as the worlds first blue jeans, the Levis® 501® Original Fit is a timeless symbol of authenticity, rebellion, and American heritage. Crafted from premium heavyweight denim, these jeans feature a straight-leg silhouette with a classic mid-rise waist and a button-fly closure—staying true to their original workwear roots. The sturdy 100% cotton construction (with select stretch options for added comfort) molds to your body over time, creating a personalized fit thats uniquely yours. The 501s signature details—like the iconic red tab, leather-like patch, and reinforced rivets—pay homage to its durable legacy. Versatile enough to dress up with a blazer or keep casual with a vintage tee, theyre a staple in every denim lovers wardrobe. Whether you prefer a rigid, unwashed look that fades beautifully with wear or a pre-washed, lived-in feel, the 501 adapts to your lifestyle while maintaining its rugged charm. From cowboys to rockstars, rebels to trendsetters, generations have made the 501 their own. More than just jeans—theyre a cultural icon. Fit note: True to size with a roomy thigh and straight leg opening for a classic, comfortable silhouette.',
      '501_jeans.jpg'),
      --- Men's leather Jacket by Boss
      (9, 6, 2, 'Casual Leather Jacket by Boss','Rugged mens leather jacket—timeless style, premium quality, perfect for any occasion - Boss.',
      'Elevate your wardrobe with this premium men''s leather jacket, expertly crafted from high-quality genuine leather for lasting durability and timeless appeal. The classic biker-inspired design features a sleek silhouette with a front zipper closure, notch lapel collar, and multiple functional pockets for everyday convenience. Soft inner lining ensures comfort while the supple leather develops a unique patina over time, personalizing to your wear. Designed for versatility, this jacket transitions effortlessly from casual daytime wear to evening sophistication, pairing perfectly with jeans, tees, or dressier layers. The medium-weight construction makes it ideal for year-round wear, offering just enough warmth without bulk. Reinforced stitching and quality hardware guarantee long-lasting performance, whether your riding or simply making a style statement. With its tailored yet comfortable fit, this jacket enhances any outfit while maintaining rugged masculinity. A true investment piece, it''s built to age gracefully, becoming more distinctive with each wear. The perfect combination of function and fashion, this leather jacket delivers unmatched confidence and edge for the modern man who values both style and substance in his everyday essentials.',
      'leather_jacket.jpg'),
      --- Men's leather Jacket by Aeropostale
      (10, 6, 4, 'Casual Leather Jacket by Aeropostale','Stylish mens leather jacket from Aeropostale, premium quality, perfect for any occasion.',
      'Step up your street style with the Aeropostale mens leather jacket, designed to deliver rugged sophistication with an urban edge. This sleek jacket features a premium faux leather construction that looks and feels luxurious, with a perfectly broken-in vibe from day one. The minimalist biker-inspired design boasts a clean front zipper closure, subtle branding, and a tailored silhouette that flatters every build. With its slightly distressed finish and matte black finish, this jacket adds instant cool to any outfit - layer it over hoodies for casual days or pair with dark denim for nightlife appeal. The lightweight construction moves with you while maintaining that coveted leather jacket structure. Inside, a soft lining ensures all-day comfort whether you''re out with friends or running errands. Aeropostale''s signature attention to detail shines through in the reinforced stitching, smooth zipper action, and discreet interior pocket. The versatile design transitions effortlessly from season to season, working as well with summer tees as with winter layers. More than just outerwear, this is a style statement that elevates your everyday look with that perfect balance of toughness and refinement.
      ','leather_jacket.jpg'),  
      --- Men's Chinos by Gap
      (11, 1, 1, 'Chinos - casual, by The Gap', 'Classic mens chinos: tailored fit, versatile colors, durable cotton blend, perfect for casual or smart-casual looks.',
      'Mens Chinos - Perfect Fit & Premium Comfort. Upgrade your wardrobe with our classic men''s chinos, designed for a sharp yet comfortable fit. Crafted from a premium cotton-blend fabric, these chinos offer a soft, breathable feel with just the right amount of stretch for unrestricted movement. The tailored slim or straight fit ensures a modern silhouette—neither too tight nor too loose—while the mid-rise waist provides a polished look that sits comfortably at the hip. The durable twill weave resists wrinkles and maintains structure, making these chinos ideal for all-day wear, whether at the office or out for casual outings. Reinforced stitching at stress points ensures long-lasting durability, while the smooth finish adds a refined touch. The fabrics slight elasticity allows for ease of motion without sagging, so you stay looking sharp from morning to night. Available in versatile colors, these chinos pair effortlessly with dress shirts, polos, or casual tees, making them a must-have for any stylish wardrobe. Designed for men who value both comfort and sophistication, these chinos strike the perfect balance between relaxed and refined.',
      'chinos.jpg'), 
      --- Men's Chinos by Boss
      (12, 1, 2, 'Chinos - casual, by Boss', 'Classic mens chinos by Boss: tailored fit, versatile colors, durable cotton blend, perfect for casual or smart-casual looks.',
      'Mens Chinos - Perfect Fit & Premium Comfort. Upgrade your wardrobe with our classic men''s chinos, designed for a sharp yet comfortable fit. Crafted from a premium cotton-blend fabric, these chinos offer a soft, breathable feel with just the right amount of stretch for unrestricted movement. The tailored slim or straight fit ensures a modern silhouette—neither too tight nor too loose—while the mid-rise waist provides a polished look that sits comfortably at the hip. The durable twill weave resists wrinkles and maintains structure, making these chinos ideal for all-day wear, whether at the office or out for casual outings. Reinforced stitching at stress points ensures long-lasting durability, while the smooth finish adds a refined touch. The fabrics slight elasticity allows for ease of motion without sagging, so you stay looking sharp from morning to night. Available in versatile colors, these chinos pair effortlessly with dress shirts, polos, or casual tees, making them a must-have for any stylish wardrobe. Designed for men who value both comfort and sophistication, these chinos strike the perfect balance between relaxed and refined.',
      'chinos.jpg'), 
      --- Sports coat by Boss
      (13, 1, 2, 'Sports coat - business casual, by Boss', 'Tailored mens sports coat - lightweight, versatile, perfect for business casual elegance.',
      'Elevate your business casual wardrobe with this impeccably tailored sports coat, designed for modern professionals who value both style and comfort. Crafted from premium wool-blend fabric with subtle stretch, this jacket offers exceptional breathability and year-round versatility. The refined slim-fit silhouette skims the body without restriction, featuring structured shoulders for a polished look and a slightly tapered waist for flattering proportions. The lightweight, wrinkle-resistant material maintains its sharp appearance throughout the workday, while the half-canvas construction ensures proper drape without bulk. Thoughtful details like functioning button cuffs, a notched lapel, and welt pockets enhance the sophisticated aesthetic. The fabric''s natural elasticity allows for comfortable movement, making it ideal for transitioning from office to evening engagements. Available in versatile neutral tones, this sports coat pairs effortlessly with dress trousers, chinos, or dark denim. The medium-weight construction provides just enough structure for professional settings while remaining comfortable for all-day wear. Designed for the modern man who demands both style and substance, this jacket delivers the perfect balance of tailored sophistication and relaxed versatility for your business casual rotation.',
      'sports_coat.jpg'), 
      --- Suit coat by Brioni
      (14, 1, 18, 'Suit coat - business perfect, by Brioni','Classic tailored suit coat - premium wool, sharp silhouette, versatile elegance.',
      'Refined Versatility: The Perfect Suit Coat for Modern Dressing. Crafted from premium wool or wool-blend fabrics, this suit coat offers a sharp yet comfortable silhouette with just the right amount of structure. The tailored fit features a gently contoured waist, natural shoulders, and a slightly tapered cut through the body for a polished look that flatters without restricting movement. What sets this coat apart is its effortless versatility. While designed to pair perfectly with matching suit trousers for formal occasions, its refined-but-relaxed proportions make it ideal for smart-casual wear too. The medium-weight fabric (180-220g) provides enough body to hold its shape while remaining comfortable all day. Pair it with dark blue jeans for an elevated weekend look - the structured shoulders and clean lines create intentional contrast with denim''s casual  texture. The fabric''s subtle luster and rich depth of color transition seamlessly from office to evening. Functional sleeve buttons and a well-proportioned lapel width keep it looking appropriate whether you''re dressing up or down. For men who want one quality coat that works as hard as they do - equally at home in the boardroom or at a dinner date when paired with jeans and loafers. The wrinkle-resistant weave ensures you''ll always look put together, while the half-canvas construction offers better drape than fused alternatives at this price point.',
      'suit_coat.jpg'), 
      --- Trench coat   
      (15, 1, 2, 'Trench coat - always perfect, by Boss', 'Classic men''s trench coat water resistant timeless style versatile layering piece.',
      'Timeless Waterproof Trench Coat Crafted for Maximum Protection and Style. This classic mens trench coat is constructed from premium waterproof cotton blend fabric treated with advanced water repellent technology to keep you dry in heavy rain. The tightly woven material blocks wind while remaining breathable for all day comfort. Reinforced stitching at stress points and double layered shoulders ensure durability season after season. The water resistant finish beads off moisture without compromising the fabrics natural look and feel. A hidden storm flap provides extra protection across the chest while the full length cut shields your legs from downpours. The inner lining features quick drying technology that wicks away moisture when worn over suits or casual layers. Designed for urban commuters and travelers this trench coat maintains its crisp silhouette even in wet conditions. The medium weight fabric drapes elegantly without bulk making it ideal for transitional weather. Metal hardware and sturdy buttons withstand repeated use while the adjustable belt allows customized fit over different outfits. From business attire to weekend wear this waterproof trench combines practical performance with refined aesthetics. The neutral color options work with any wardrobe while the timeless design ensures years of reliable service. Machine washable for easy care without losing its protective qualities.',
      'trench_coat.jpg'),

      -- Polo Shirt by The Gap
      (16, 4, 1, 'Polo shirt, The Gap', 'Classic short-sleeve polo shirt by The Gap offering comfort style and value for everyday wear',
      'Classic Short Sleeve Value Polo Shirt The Gap - Premium Fit & Quality Materials. Upgrade your everyday wardrobe with our short sleeve value polo shirt, designed for comfort, style, and durability. Crafted from high-quality fabric, this polo offers a soft, breathable feel that keeps you cool and comfortable all day. The tailored fit provides a polished look without sacrificing ease of movement, making it perfect for work, casual outings, or weekend wear.The reinforced collar and cuffs maintain structure wash after wash, while the moisture-wicking fabric helps you stay fresh in any setting. Available in a range of versatile colors, this polo pairs effortlessly with chinos, jeans, or dress pants for a sharp, put-together appearance. Whether youre dressing for the office, a lunch date, or a relaxed day out, this affordable yet premium polo delivers unbeatable value without compromising on fit or fabric quality. Machine washable for easy care, its a must-have staple for any modern wardrobe.',
      'polo_shirt.jpg'),

      -- Polo Shirt by Boss
      (17, 4, 2, 'Polo shirt, Boss', 'Classic short-sleeve polo shirt by Boss offering comfort style and value for everyday wear',
      'Classic Short Sleeve Value Polo Shirt The Gap - Premium Fit & Quality Materials. Upgrade your everyday wardrobe with our short sleeve value polo shirt, designed for comfort, style, and durability. Crafted from high-quality fabric, this polo offers a soft, breathable feel that keeps you cool and comfortable all day. The tailored fit provides a polished look without sacrificing ease of movement, making it perfect for work, casual outings, or weekend wear.The reinforced collar and cuffs maintain structure wash after wash, while the moisture-wicking fabric helps you stay fresh in any setting. Available in a range of versatile colors, this polo pairs effortlessly with chinos, jeans, or dress pants for a sharp, put-together appearance. Whether youre dressing for the office, a lunch date, or a relaxed day out, this affordable yet premium polo delivers unbeatable value without compromising on fit or fabric quality. Machine washable for easy care, its a must-have staple for any modern wardrobe.',
      'polo_shirt.jpg'),

      -- Shirts and Blouses
      (18, 2, 11, 'Calvin Klein Cotton Shirt', 'Premium cotton dress shirt', 
      'Calvin Klein''s signature dress shirt combines modern tailoring with premium cotton for a sophisticated look. Features spread collar, French cuffs, and subtle logo embroidery. Perfect for business meetings or formal occasions. The shirt offers a contemporary fit that''s neither too tight nor too loose, making it ideal for layering under suits or wearing on its own. Machine washable for easy care.',
      'not_available.jpg'),
      
      (19, 3, 8, 'Zara Silk Blouse', 'Elegant silk blouse for professional wear',
      'This sophisticated Zara silk blouse elevates any professional wardrobe with its luxurious feel and timeless design. Made from 100% silk with a relaxed fit, it features subtle pleating details and mother-of-pearl buttons. The versatile design transitions seamlessly from boardroom to after-work events. Available in classic colors, it pairs beautifully with tailored trousers or pencil skirts.',
      'not_available.jpg'),
      
      (20, 2, 12, 'Tommy Hilfiger Polo Shirt', 'Classic polo in signature colors',
      'The iconic Tommy Hilfiger polo shirt represents preppy American style at its finest. Crafted from soft cotton pique with the classic three-button placket and ribbed collar and cuffs. Features the signature flag logo and comes in an array of vibrant colors. This versatile piece works equally well for golf, casual Fridays, or weekend outings with friends.',
      'not_available.jpg'),
      
      -- Pants and Dresses
      (21, 1, 13, 'Ralph Lauren Chinos', 'Premium chino pants in classic fit',
      'Polo Ralph Lauren''s essential chinos combine comfort with refined style. Made from premium cotton twill with a classic straight-leg fit, these versatile pants work for both casual and smart-casual occasions. Features include flat-front styling, belt loops, and the signature pony logo. The timeless design and quality construction make these a wardrobe staple that pairs well with everything from polo shirts to blazers.',
      'not_available.jpg'),
      
      (22, 8, 8, 'Zara Midi Dress', 'Contemporary midi dress in flowing fabric',
      'This elegant Zara midi dress embodies modern femininity with its flowing silhouette and contemporary design. Made from lightweight fabric that drapes beautifully, it features a fitted bodice and A-line skirt that flatters all body types. The versatile design can be dressed up with heels for evening events or down with sneakers for casual daywear. Perfect for the fashion-conscious woman who values both style and comfort.',
      'not_available.jpg'),

      -- Sportswear
      (23, 7, 6, 'Nike Athletic T-Shirt', 'Performance t-shirt with moisture-wicking technology',
      'Nike''s performance athletic t-shirt is engineered for serious athletes and fitness enthusiasts. Features advanced Dri-FIT technology that wicks moisture away from the skin to keep you dry and comfortable during intense workouts. The lightweight, breathable fabric moves with your body, while flatlock seams reduce chafing. Perfect for running, gym workouts, or any high-intensity activity.',
      'not_available.jpg'),
      
      (24, 7, 7, 'Adidas Track Pants', 'Classic athletic pants with signature stripes',
      'These iconic Adidas track pants feature the brand''s signature three-stripe design and are perfect for both athletic activities and casual wear. Made from lightweight, breathable fabric with an elastic waistband and ankle cuffs for a comfortable fit. The classic design has been a favorite among athletes and fashion enthusiasts for decades, offering both style and functionality.',
      'not_available.jpg'),
      
      (25, 7, 15, 'Under Armour Sports Bra', 'High-support sports bra for intense workouts',
      'Under Armour''s high-performance sports bra provides maximum support and comfort during high-intensity workouts. Features compression fit, moisture-wicking fabric, and strategic mesh panels for enhanced breathability. The racerback design allows for full range of motion, while the wide elastic band provides secure fit without rolling. Essential gear for serious female athletes.',
      'not_available.jpg'),
      
      -- Outerwear
      (26, 6, 10, 'Uniqlo Down Jacket', 'Ultra-light down jacket for winter warmth',
      'Uniqlo''s revolutionary ultra-light down jacket combines exceptional warmth with incredible portability. Filled with premium down and covered in water-repellent fabric, it provides excellent insulation while remaining surprisingly lightweight. The jacket packs down into its own travel pouch, making it perfect for travel or unexpected weather changes. Features include elastic cuffs, adjustable hem, and multiple pockets for convenience.',
      'not_available.jpg'),
      
      (27, 6, 14, 'Lacoste Windbreaker', 'Classic windbreaker with crocodile logo',
      'The Lacoste windbreaker embodies the brand''s sporting heritage with its lightweight design and water-resistant finish. Perfect for unpredictable weather, this versatile jacket features the iconic crocodile logo, adjustable hood, and zippered pockets. The relaxed fit allows for easy layering over sweaters or hoodies, making it an essential piece for transitional seasons.',
      'not_available.jpg'),
      
      -- Footwear
      (28, 4, 6, 'Nike Running Shoes', 'Professional running shoes with advanced cushioning',
      'Nike''s latest running shoes feature cutting-edge technology designed to enhance performance and comfort. The advanced cushioning system absorbs impact while providing responsive energy return with each step. Breathable mesh upper keeps feet cool and dry, while the durable rubber outsole provides excellent traction on various surfaces. Perfect for serious runners and casual joggers alike.',
      'not_available.jpg'),
      
      (29, 4, 7, 'Adidas Lifestyle Sneakers', 'Casual sneakers perfect for everyday wear',
      'These versatile Adidas lifestyle sneakers combine comfort with street-style aesthetics. Featuring the brand''s signature three-stripe design and classic silhouette, they''re perfect for everyday wear. The cushioned midsole provides all-day comfort, while the durable construction ensures long-lasting performance. Available in multiple colorways to match any personal style.',
      'not_available.jpg'),
      
      -- Accessories
      (30, 5, 11, 'Calvin Klein Leather Belt', 'Premium leather belt with signature buckle',
      'Calvin Klein''s premium leather belt is a timeless accessory that completes any sophisticated look. Made from genuine leather with the brand''s signature rectangular buckle, it adds a touch of elegance to both business and casual attire. The classic design and quality construction ensure this belt will remain a wardrobe staple for years to come.',
      'not_available.jpg'),
      
      (31, 5, 12, 'Tommy Hilfiger Watch', 'Classic analog watch with leather strap',
      'The Tommy Hilfiger classic watch combines traditional timekeeping with contemporary style. Features a stainless steel case, analog display, and genuine leather strap for comfort and durability. The clean, minimalist design makes it suitable for both professional and casual settings. Water-resistant construction ensures reliable performance in various conditions.',
      'not_available.jpg')

    ON CONFLICT (id) DO NOTHING;