
/* ============================================================================

                        Code samples for Chapter 11

    1) code for logical replication and related topics is in the file 
    psql_scripts/replication/product_replication_setup.sql
    It is part of the overall replication setup scripts and does not need to be
    run separately.               
    2) code to show the alternate way to populate the DWH is shown below
        A) Database and table creation
        - Create a database central_analytics_bcp
        - Define the same tables as in central_analytics
        B) Bulk load data using the \copy command from psql
        - Uses the \copy command to bulk load data using psql commands  
        - see psql_scripts/sample_scripts/chapter_11.sh 

============================================================================ */ 

-- Part 2: Alternate way to populate the DWH using bulk copy

-- create the central_analytics_bcp database
DROP DATABASE IF EXISTS central_analytics_bcp WITH (FORCE);

CREATE DATABASE central_analytics_bcp;

\c central_analytics_bcp

CREATE SCHEMA product;
CREATE SCHEMA customer;
CREATE SCHEMA sales;

\echo '--> Creating the search path at the database level'

-- the analytics schema will be used for views and reporting
ALTER DATABASE central_analytics SET SEARCH_PATH TO product, customer, sales; -- permanent change
SET SEARCH_PATH TO product, customer, sales;  --- make sure path is available in current session


-- product tables

CREATE TABLE product.category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product.brand (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product.country_of_origin (
    brand_id INTEGER PRIMARY KEY REFERENCES brand (id),
    --- three digit ISO 3166-1 A-3
    alpha3_code VARCHAR(3) NOT NULL,
    name TEXT
);

CREATE TABLE product.product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id INTEGER NOT NULL REFERENCES product.category (id),
    brand_id INTEGER NOT NULL REFERENCES product.brand (id),
    label VARCHAR(50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50)
);

CREATE TABLE product.product_variant (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product.product(id) ON DELETE CASCADE,
    attributes JSONB
);


CREATE TABLE product.product_variant_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant_id INTEGER NOT NULL REFERENCES product.product_variant (id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    -- DATERANGE where the lower bound is inclusive, and the upper bound is exclusive.
    validity DATERANGE NOT NULL,
    current BOOLEAN NOT NULL DEFAULT false
);

-- customer table with the PII fields masked

CREATE TABLE customer.customer (
    id UUID PRIMARY KEY,
    -- PII fields are masked (see replication setup scripts for column-level filtering)
    first_name VARCHAR(50) DEFAULT 'masked',
    last_name VARCHAR(50) DEFAULT 'masked',
    phone_numbers JSONB DEFAULT '{"home": "+1 (555) 123-345", "mobile": "+1 (555) 456-789"}',
    street_address VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(50) NOT NULL,
    origin VARCHAR(4) NOT NULL
);

-- sales tables

CREATE TABLE sales.sales_transaction(
    id UUID PRIMARY KEY,
    transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer_id UUID REFERENCES customer (id),
    origin VARCHAR(4)
);

CREATE TABLE sales.sales_transaction_line (
    id UUID PRIMARY KEY,
    sales_transaction_id UUID REFERENCES sales_transaction (id),
    product_variant_id INTEGER NOT NULL REFERENCES product_variant (id),
    qty INTEGER,
    price_at_sale NUMERIC(10, 2)
);

-- =================================================================