-- \echo '--> Successfully connected to database: ecommerce_reference_data'


-- =================================================================
--  SECTION 2: EXTENSIONS AND CUSTOM TYPES
-- =================================================================

-- \echo '--> Creating extensions...'
-- btree_gist is required for using the GIST exclusion constraint on a DATERANGE.
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- \echo '--> Creating custom ENUM types...'
-- Using ENUMs helps ensure data integrity for controlled vocabularies.
CREATE TYPE sales_geo AS ENUM ('EU', 'US');
CREATE TYPE sales_currency AS ENUM ('USD', 'EURO');


-- =================================================================
--  SECTION 3: TABLE DEFINITIONS
-- =================================================================

-- \echo '--> Creating application tables...'

CREATE TABLE product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE product (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product (id),
    product_id INTEGER NOT NULL REFERENCES product (id),
    label VARCHAR (50) NOT NULL,
    shortdescription VARCHAR(200) NOT NULL,
    longdescription TEXT,
    image_filename VARCHAR(50)
);

CREATE TABLE product_variant (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    attributes JSONB
);

CREATE TABLE product_variant_price (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_variant_id INTEGER NOT NULL REFERENCES product_variant (id) ON DELETE CASCADE,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0),
    currency sales_currency NOT NULL,
    /*
     * DEV NOTE on `geography`:
     * Using VARCHAR(3) instead of the `sales_geo` ENUM is the correct workaround
     * for a known limitation in PostgreSQL where filtered logical replication
     * (e.g., WHERE geography = 'US') does not work with ENUM types.
    */
    geography VARCHAR(3) NOT NULL,
    -- DATERANGE where the lower bound is inclusive, and the upper bound is exclusive.
    validity DATERANGE NOT NULL,
    current BOOLEAN NOT NULL DEFAULT false,

    -- [IMPROVEMENT] Constraint to ensure currency matches the geography.
    CONSTRAINT check_currency_geo_consistency CHECK (
        (geography = 'US' AND currency = 'USD') OR
        (geography = 'EU' AND currency = 'EURO')
    ),

    -- Ensures that there are no overlapping price validity periods for the same product variant and geography.
    EXCLUDE USING GIST (product_variant_id WITH =, geography WITH =, validity WITH &&)
);

-- Set REPLICA IDENTITY to FULL for the table that has row-filtered replication.
-- This ensures that old row data is available for logical replication updates.
ALTER TABLE product_variant_price REPLICA IDENTITY FULL;


-- =================================================================
--  SECTION 4: TEST DATA INSERTION
-- =================================================================

-- \echo '--> Inserting test data...'
-- Using OVERRIDING SYSTEM VALUE to control the IDs for predictable testing.
INSERT INTO product (id, label, description)
    VALUES
        (1, 'Pants', 'long trousers'),
        (2, 'Shirts', 'long sleeve and short sleeve shirts'),
        (3, 'Blouses', 'long sleeve and short sleeve shirts for women'),
        (4, 'Footwear', 'Mens and womens dress shoes')
    ON CONFLICT (id) DO NOTHING;

INSERT INTO product (id, label, description)
    VALUES
        (1, 'Gap', 'The Gap'),
        (2, 'Boss', 'Boss'),
        (3, 'Diesel', 'Diesel'),
        (4, 'Aéropostale',' Aéropostale Inc., is an American shopping mall–based retailer.'),
        (5, 'Levis', 'Levi Strauss & Co') -- Removed apostrophe for simplicity in labels
    ON CONFLICT (id) DO NOTHING;

INSERT INTO product (id, product_id, product_id, label, shortdescription)
    VALUES
        (1, 2, 1, 'Mens Classic Oxford Shirt', 'Timeless mens Oxford shirt in 100% cotton.'),
        (2, 2, 3, 'Mens Diesel T-Shirt', 'Graphic T-shirt from Diesel.'),
        (3, 1, 5, '501 Original Fit Jeans', 'The original blue jean since 1873.')
    ON CONFLICT (id) DO NOTHING;

INSERT INTO product_variant (id, product_id, attributes)
    VALUES
        (1, 1, '{"color": "light blue", "size": "M"}'),
        (2, 1, '{"color": "white", "size": "L"}'),
        (3, 3, '{"color": "stonewash", "size": "32x32"}')
    ON CONFLICT (id) DO NOTHING;

INSERT INTO product_variant_price (id, product_variant_id, price, currency, geography, validity, current)
    VALUES
        (1, 1, 31.00, 'EURO', 'EU', '[2025-06-01,)', true),
        (2, 1, 29.75, 'EURO', 'EU', '[2025-01-01, 2025-06-01)', false),
        (3, 1, 33.50, 'USD', 'US', '[2025-01-01, 2025-06-01)', false),
        (4, 1, 35.00, 'USD', 'US', '[2025-06-01,)', true)
    ON CONFLICT (id) DO NOTHING;


-- =================================================================
--  SECTION 5: STORED PROCEDURES AND MAINTENANCE QUERIES
-- =================================================================

-- \echo '--> Creating stored procedures for data maintenance...'

-- [IMPROVEMENT] Rewritten procedure to be more efficient.
CREATE OR REPLACE PROCEDURE update_current_price_flags()
    LANGUAGE SQL
    AS $$
    -- This single UPDATE is more efficient than iterating.
    -- It sets 'current' to true if the current date falls within the
    -- validity range, and false otherwise.
    UPDATE product_variant_price
    SET current = (validity @> current_date);
$$;

-- \echo '--> Example maintenance queries:'
-- \echo '    1. To run the procedure to update all flags: CALL update_current_price_flags();'
-- \echo '    2. To find products/variants without a current valid price:'

-- [IMPROVEMENT] Query to find variants without a current price.
SELECT
    v.id AS variant_id,
    p.label AS product_label
FROM
    product_variant v
JOIN
    product p ON v.product_id = p.id
WHERE NOT EXISTS (
    SELECT 1
    FROM product_variant_price pvp
    WHERE pvp.product_variant_id = v.id AND pvp.current = true
);
